### ISSUE TITLE
QR scanner not working in Chrome mobile browser

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#1001]
![зображення_viber_2021-04-15_13-27-12](https://user-images.githubusercontent.com/69896204/114880607-df691700-9e0a-11eb-98a3-8c8b77e4e3ec.png)
![scan err](https://user-images.githubusercontent.com/69896204/114880805-117a7900-9e0b-11eb-8a1f-04647122637c.png)

and then Data donate Error :
![11](https://user-images.githubusercontent.com/69896204/114881127-63bb9a00-9e0b-11eb-9ee1-c2a818f6d085.png)
![22](https://user-images.githubusercontent.com/69896204/114881150-68804e00-9e0b-11eb-8b2a-94cd2aa64ee0.png)
![33](https://user-images.githubusercontent.com/69896204/114881175-6e762f00-9e0b-11eb-937a-8fbce0aae18e.png)

Chrome70.0.3538.80

**Comment by Liubov-crypto** [comment]
Got this error on Android apk:
![зображення_viber_2021-04-26_13-49-18](https://user-images.githubusercontent.com/69896204/116071992-39819c00-a697-11eb-8e24-7f702a62ce46.png)

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up again.
