### ISSUE TITLE
Display name and avatar are missed in wallet notifications

### ISSUE THREAD

**Issue by etharner** [aeternity/superhero-wallet#1008]
![image](https://user-images.githubusercontent.com/7098449/114897496-a2297700-9e54-11eb-88af-dee77476c9aa.png)

**Comment by paolomolo** [comment]
For this specific notification we don't need a name and avatar at all and should instead only show the message.
What would be other notifications where name and avatar are missing as well?

**Comment by Liubov-crypto** [comment]
@paolomolo @onvisions maybe we should update the design for this page.
