### ISSUE TITLE
Truncated texts in the wallet

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#1012]
IOS app:
<img width="411" alt="Wire 2021-04-16 at 07-39-48" src="https://user-images.githubusercontent.com/69896204/114991857-be540500-9ea2-11eb-8dca-8e447dc9ac89.png">

Chrome ext/Web wallet in Chrome: 
![send tips](https://user-images.githubusercontent.com/69896204/114998663-da0ed980-9ea9-11eb-9bd4-42f9bedd853d.png)

truncated hash:
![tx det](https://user-images.githubusercontent.com/69896204/114998699-e2ffab00-9ea9-11eb-8db9-4d15088d837c.png)
![hash](https://user-images.githubusercontent.com/69896204/114998715-e5620500-9ea9-11eb-8473-fd68c7da0e08.png)

![chrome ext](https://user-images.githubusercontent.com/69896204/114992442-6ff33600-9ea3-11eb-95d5-158249bbba71.png)
![Безіменний 2](https://user-images.githubusercontent.com/69896204/114993120-29520b80-9ea4-11eb-8271-8554558b7a48.png)

![333](https://user-images.githubusercontent.com/69896204/114993856-e0e71d80-9ea4-11eb-877d-db9e0ed92495.png)

![ккк](https://user-images.githubusercontent.com/69896204/115002089-037d3480-9ead-11eb-8460-3c337f2ddd19.png)

**Comment by Liubov-crypto** [comment]
White text on a white field when renaming a sub-account:
![white on white](https://user-images.githubusercontent.com/69896204/115048569-60dfa880-9ee2-11eb-95d6-106c85b4f03d.png)

**Comment by davidyuk** [comment]
cc: @onvisions

**Comment by Liubov-crypto** [comment]
These issues have been fixed in the new design. May be closed.

**Comment by subhod-i** [comment]
Closing in lieu with the new design
