### ISSUE TITLE
The part of the text comes out under the bottom panel

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#1013]
When scrolling, part of the text comes out under the bottom panel (Notification and Tx details section (from time to time):
![notification](https://user-images.githubusercontent.com/69896204/115006244-52c56400-9eb1-11eb-8d22-e401f9a6a14c.png)

on develop branch d8c89dd / v.0.6.0

**Comment by davidyuk** [comment]
cc: @etharner

**Comment by imollov** [comment]
fixed
