### ISSUE TITLE
Inform user about lost connection instead of reseting state

### ISSUE THREAD

**Issue by imollov** [aeternity/superhero-wallet#1019]
In the recording below I'm turning off my internet connection.

![recording (16)](https://user-images.githubusercontent.com/482351/115250131-f4f37f00-a131-11eb-86c5-4681df0c21b6.gif)

Could be very confusing and stressful for the user to see their balance go to 0 without explanation, in case of connection interruption.

**Comment by davidyuk** [comment]
cc: @onvisions

**Comment by onvisions** [comment]
I agree with the UX issue described by @imollov above. So we need placeholder design for "lost connection" messgae to be displayed across the wallet UI (on different screens) if I got your point correctly? I'll create task for this one.

**Comment by Liubov-crypto** [comment]
The old design bug. Can be closed.
