### ISSUE TITLE
Wallet changes the default name by himself

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/superhero-wallet#1024]
After the payment transaction, the name in the account was changed by itself, although by default I set a different name.

_Originally posted by @Liubov-crypto in https://github.com/aeternity/superhero-wallet/issues/1016#issuecomment-822399009_

**Comment by Liubov-crypto** [comment]
Tested, I can't reproduce this error on develop branch  68a2ffe / v.0.6.0

**Comment by CedrikNikita** [comment]
fixed by #1023
