### ISSUE TITLE
Error when sending FT to .chain name

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#1028]
![chainname](https://user-images.githubusercontent.com/69896204/115547801-61e05380-a2af-11eb-96bc-88d51f88354c.png)
![ttt](https://user-images.githubusercontent.com/69896204/115547810-6442ad80-a2af-11eb-9ef2-7342df8210bd.png)
![11111](https://user-images.githubusercontent.com/69896204/115548061-b1268400-a2af-11eb-94a0-7f5fab9a5822.png)

develop 68a2ffe / v.0.6.0

**Comment by onvisions** [comment]
Error messages should be displayed in the modal template for the wallet and not in this wide version (as in the screenshot with error above).

**Comment by davidyuk** [comment]
@onvisions can you send a link to proper designs?

**Comment by onvisions** [comment]
@davidyuk , I am discussing here only the issue with full screen popups in web wallet suggesting to use the regular modal template. Its design is in "Superhero Wallet UI" (FIgma) and there are several examples of different modals included. I won't publish the direct link as I was adviced before not to include links to internal resources in our public discussions.

**Comment by thepiwo** [comment]
I think sending fungible tokens should forbid send to name functionality a its not native to AEX-9
