### ISSUE TITLE
AmountInput: Validate referenced props

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-wallet#1031]
https://github.com/aeternity/superhero-wallet/blob/d02410462c1d3d9e31d50f92f1214791c97803b1/src/popup/router/components/AmountInput.vue#L6-L7

https://github.com/aeternity/superhero-wallet/blob/d02410462c1d3d9e31d50f92f1214791c97803b1/src/popup/router/components/AmountInput.vue#L9

https://github.com/aeternity/superhero-wallet/blob/d02410462c1d3d9e31d50f92f1214791c97803b1/src/popup/router/components/AmountInput.vue#L36

cc: @etharner

**Comment by peronczyk** [comment]
I'm not 100% sure what you mean by "Validate referenced props", but the AmountInput has been replaced with the new version recently: https://github.com/aeternity/superhero-wallet/pull/2116

**Comment by davidyuk** [comment]
I think I meant to use component's props instead of `$attrs`. The type of `$attrs` properties can't be validated the way vue validates props (before introducing typescript).

**Comment by peronczyk** [comment]
@davidyuk sure, and the new <InputAmount> input has no logic that is based on the `$attrs` so this covers your suggested change.
