### ISSUE TITLE
Invalid invite when swtiching networks

### ISSUE THREAD

**Issue by imollov** [aeternity/superhero-wallet#1034]
create invite link with 1AE on testnet

![Screenshot 2021-04-22 at 19 42 12](https://user-images.githubusercontent.com/482351/115752598-eb248280-a3a2-11eb-9779-a23b1182dcbf.png)

switch to mainnet

![Screenshot 2021-04-22 at 19 42 36](https://user-images.githubusercontent.com/482351/115752606-ee1f7300-a3a2-11eb-880a-c5164260e62b.png)

tested on 17002cd3308b8e19da1987b2694d2c065a511177

**Comment by davidyuk** [comment]
I don't like to make features aware of network switching (for example, to store an array of invite links for each network). Also, I don't see explicit misbehavior there. Network switching is for advanced users and I think they should be ready for some not super obvious things like this.

**Comment by imollov** [comment]
> I don't like to make features aware of network switching (for example, to store an array of invite links for each network). Also, I don't see explicit misbehavior there. 

> By the way, if you create a subaccount on testnet and sent to it some AE, after switching to mainnet you will see the same, should it be considered a bug as well?

In my opinion there's misbehavior in both scenarios. Even if 3rd party devs use it to test their aepps it could lead to confusion and losing confidence in the product.

> Network switching is for advanced users and I think they should be ready for some not super obvious things like this.

That said the issue is rendered unimportant. Feel free to close.
