### ISSUE TITLE
Oversized modals in the Web wallet

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#1036]
![send tip conf](https://user-images.githubusercontent.com/69896204/116063086-3681ae00-a68d-11eb-8a23-272dec418d35.png)
![rrr](https://user-images.githubusercontent.com/69896204/116063092-384b7180-a68d-11eb-8b0d-dab57d41fd9e.png)

**Comment by davidyuk** [comment]
@onvisions do you have an idea how they should be sized?
