### ISSUE TITLE
Wallet phishing check blocks running local service (i.e. Plex)

### ISSUE THREAD

**Issue by venimus** [aeternity/superhero-wallet#107]
popular home streaming Plex (https://www.plex.tv/) is running a local web server `https://127.0.0.1:32400` which is not accessible while wallet extension is active, probably because phishing check does not redirect properly. There is a blank page.

**Comment by petbaik** [comment]
Hey @venimus can you try with https://github.com/aeternity/superhero-wallet/pull/110
