### ISSUE TITLE
Broken truncated text in Safari

### ISSUE THREAD

**Issue by imollov** [aeternity/superhero-wallet#1102]
<img width="345" alt="Screenshot 2021-05-21 at 18 10 51" src="https://user-images.githubusercontent.com/482351/119159520-faf5bc00-ba5f-11eb-995d-28f10510f262.png">

**Comment by Liubov-crypto** [comment]
This error is reproduced on the develop branch: commit c20856f / v.0.7.0

![bug with names](https://user-images.githubusercontent.com/69896204/121357603-98932b80-c93a-11eb-94ef-ab4366cfc6e8.png)

**Comment by Liubov-crypto** [comment]
@etharner can we reopen and fix this error?
