### ISSUE TITLE
Use the new backend tip await endpoint

### ISSUE THREAD

**Issue by kenodressel** [aeternity/superhero-wallet#1133]
There is a new endpoint the backend: https://raendom-backend.z52da5wt.xyz/docs/#/tips/get_tips_await_tip__tipId_
This should allow the wallet much easier to wait for recently submitted tips. It might also be enough to omit the contract initialization all together?

**Comment by mradkov** [comment]
> It might also be enough to omit the contract initialization all together?

Isn't this also needed for sending a tip?

**Comment by kenodressel** [comment]
True but the really expensive part is fetching the state which should not be necessary anymore?

**Comment by imollov** [comment]
> True but the really expensive part is fetching the state which should not be necessary anymore?

Currently only `tip_token`, `retip_token` and `unclaimed_for_url` are called of the Tipping contract methods. No fetching of awaited tips.

**Comment by kenodressel** [comment]
So we are waiting until the tx is mined before show the "TX SUCCESS" screen?

**Comment by imollov** [comment]
> So we are waiting until the tx is mined before show the "TX SUCCESS" screen?

Correct. 

Yet, we have the pending tx listed before that.

**Comment by kenodressel** [comment]
Okay then this is not an issue :)
