### ISSUE TITLE
Deeplink Issue iOS

### ISSUE THREAD

**Issue by maxkpower** [aeternity/superhero-wallet#1138]
When tipping or commenting only the web wallet loads, even though the app is installed.

**Comment by imollov** [comment]
Could not reproduce with wallet v0.7.2 from AppStore on iOS device v14.7.

Please test again and post more info if the issue still occurs.

**Comment by imollov** [comment]
Could not reproduce with @maxkpower iOS version (14.4) either.

Latest develop works as expected on iOS simulator and device.
