### ISSUE TITLE
Truncated hash view

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#1141]
Truncated hash view:
![pending tx](https://user-images.githubusercontent.com/69896204/122924116-16f5c180-d36e-11eb-9bdd-d92afaead5dd.png)

commit 9487d5a / v.0.7.2

**Comment by onvisions** [comment]
Design solution for too long tx hashes and addresses has been already discussed. The proposed fix to the issue described is to use mono space variant of the font (IBM Plex Mono) with font-size: 10px, font-weight: medium and line-height: 16px; The specific styling of the placeholders can be seen on the transaction screens in the updated  wallet UI prototype (Figma).

**Comment by CedrikNikita** [comment]
fixed in https://github.com/aeternity/superhero-wallet/pull/1119
