### ISSUE TITLE
Reduce errors popped up to user

### ISSUE THREAD

**Issue by imollov** [aeternity/superhero-wallet#1146]
* Unhandled JS errors do not have any useful information for the user
* Pop ups interrupt user flow and result in bad UX
* Looping errors make the app almost impossible to use

Example:

![Screenshot 2021-06-23 at 16 06 05](https://user-images.githubusercontent.com/482351/123101640-f0eb2280-d43c-11eb-8e6c-bd5af95a30fe.png)

**Comment by kenodressel** [comment]
Discussion: Lets disable the error modals in production. This can be done via NODE_ENV
