### ISSUE TITLE
Provide default value when adding own node

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/superhero-wallet#1151]
We should leave a default value for the compiler url field pointing to the current hosted compiler, so people can more easily try out their own node without having to mess with setting up a compiler, too. E.g. :

![image](https://user-images.githubusercontent.com/11761828/123441614-5aea0000-d5d4-11eb-9935-9175201294cc.png)

**Comment by etharner** [comment]
> We should leave a default value for the compiler url field pointing to the current hosted compiler, so people can more easily try out their own node without having to mess with setting up a compiler, too. E.g. :
> 
> ![image](https://user-images.githubusercontent.com/11761828/123441614-5aea0000-d5d4-11eb-9935-9175201294cc.png)

Agree, maybe even provide default link for middleware as well
