### ISSUE TITLE
Confusing wording in permissions

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-wallet#1158]
![Screenshot 2021-06-29 at 08 44 59](https://user-images.githubusercontent.com/9007851/123743712-4b113b00-d8b6-11eb-83ba-b40b68cbb75e.png)

From my perspective "Don't ask for message signing", doesn't mean "sign arbitrary messages on my behalf" (as it actually works), I would understand it as "refuse message signing requests from aepp".

cc: @onvisions @maxkpower

**Comment by paolomolo** [comment]
```Automatically sign messages on my behalf```  Maybe?

**Comment by Liubov-crypto** [comment]
@paolomolo do we need to change the wording here or can we close it?
![perm1](https://user-images.githubusercontent.com/69896204/193255273-911ede7c-2fe3-46a3-83be-51d64bda35a2.png)

**Comment by paolomolo** [comment]
Let's update the wording to make it clearer to the user what they are allowing

**Comment by CedrikNikita** [comment]
fixed by #1745
