### ISSUE TITLE
Missing aex9 tx

### ISSUE THREAD

**Issue by kenodressel** [aeternity/superhero-wallet#1175]
**Describe the bug**
The wallet does not show all aex9 transactions from the middleware.

**To Reproduce**
Screenshot: 
![image](https://user-images.githubusercontent.com/765921/124471868-b4ed8100-dd9d-11eb-890e-57acad2ba736.png)

compare it with the result of the query:
https://mainnet.aeternity.io/mdw/aex9/transfers/to/ak_2QTYfJmtn6qcEU7u8xAySpWTSAV2nvUirKTUhqrvxk5srJVscc

**Expected behavior**
Should show all 9 transactions.

**Comment by CedrikNikita** [comment]
Can it be that the missing transactions are actually not in this chunk of transactions time frame?
