### ISSUE TITLE
Retip does not work on mobile browser

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#1179]
If I use a mobile browser and web wallet, then retip of posts from the superhero feed will not work:
![Wire 2021-07-05 at 16-35-38](https://user-images.githubusercontent.com/69896204/124500515-9486ec00-ddc8-11eb-991f-84f05eff8d55.png)
![Wire 2021-07-05 at 16-35-48](https://user-images.githubusercontent.com/69896204/124500520-95b81900-ddc8-11eb-8bae-3f99d8f16cec.png)

same on product.

**Comment by CedrikNikita** [comment]
fixed in https://github.com/aeternity/superhero-wallet/pull/1225

**Comment by CedrikNikita** [comment]
fixed in #1225
