### ISSUE TITLE
Show the correct balance of fungible tokens after a transaction

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#1197]
The balance of Fungible tokens is not updated after the transaction, I need to refresh the wallet to be correct.

Reproducible on develop branch.

**Comment by Liubov-crypto** [comment]
Agree. In the latest version of the wallet, the balance of the Fungible tokens is updated correctly, but you have to wait a while.

**Comment by Liubov-crypto** [comment]
This issue is still reproducible on the current development branch https://github.com/aeternity/superhero-wallet/commit/af33bd8c7921ca07b3949335dfd5398d0eec9223

**Comment by Liubov-crypto** [comment]
Can't reproduce this bug on the current product branch. Feel free to close it.

**Comment by subhod-i** [comment]
Duplicate #1505
