### ISSUE TITLE
Service on that phishing check depends looks broken

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-wallet#1223]
https://github.com/aeternity/superhero-wallet/blob/ddbb32b724833f3a69164e470709bb557bebb812/src/popup/utils/phishing-detect.js#L3

I'm trying to call it with some url, but getting 502 error:
https://etherscamdb.info/api/check/example.com
https://etherscamdb.info/api/check/http%3A%2F%2Fexample.com

Proposing to use a different service or to remove this check completelly.

**Comment by kenodressel** [comment]
Lets remove the service.
