### ISSUE TITLE
A drop-down menu with tokens is hidden 

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#1288]
A drop-down menu with tokens is hidden in Safari browser ver. 14.1.2 (16611.3.10.1.6):
![invisible drop-down in safari ](https://user-images.githubusercontent.com/69896204/133415094-4f6832d4-739f-4818-9f2b-d9d9e250d4ed.png)

Reproducible on develop and product branch.

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up again.
