### ISSUE TITLE
Visual bugs on Buy AE Tokens page

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#1298]
Got these small visual bugs when tested PR #1295 

When I choose ATOM, AVAX, XLM I see the wrong name wallet address: 

![tokens](https://user-images.githubusercontent.com/69896204/134334120-2813abbe-b46c-406e-ac64-b83b7365ec30.png)

When clicking on «don’t have one» - redirecting to the empty page. 

The Continue button is not visible and another text is hard to see:
![continue button is invisible](https://user-images.githubusercontent.com/69896204/134334405-61631fe6-88da-41db-9114-ec3fcafdb595.png)

I can move the wallet screen to the right in Safari and FF browsers:
![I can move screen to the right ](https://user-images.githubusercontent.com/69896204/134334593-25dae6b7-c040-4433-9ef4-58d827e0bb41.png)

White stripes in web wallet in FF browser and FF extension:
![tokens](https://user-images.githubusercontent.com/69896204/134334745-06f57f95-d2db-478e-b004-4f82c2a521bd.png)

The download button is very large:
![big button](https://user-images.githubusercontent.com/69896204/134334897-1b90cd2d-492f-4e69-9807-a3cd3e1135c3.png)

The service was unavailable from time to time:
![unavail](https://user-images.githubusercontent.com/69896204/134335100-f0aa8b61-3708-45cf-925c-fc45bcfd389d.png)

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up again
