### ISSUE TITLE
Current testing bugs

### ISSUE THREAD

**Issue by etharner** [aeternity/superhero-wallet#1316]
I suggest for @Liubov-crypto to maintain this list of issues they're repeating > 1 time.
- https://github.com/aeternity/superhero-wallet/issues/1268
- https://github.com/aeternity/superhero-wallet/issues/1317
- https://github.com/aeternity/superhero-wallet/issues/1315
- https://github.com/aeternity/superhero-wallet/issues/1306
- https://github.com/aeternity/superhero-wallet/issues/1275
- https://github.com/aeternity/superhero-wallet/issues/1333
- https://github.com/aeternity/superhero-wallet/issues/1355
- https://github.com/aeternity/superhero-wallet/issues/639
- https://github.com/aeternity/superhero-wallet/issues/1386
- https://github.com/aeternity/superhero-wallet/issues/1385

**Comment by CedrikNikita** [comment]
We don't need such list anymore.
