### ISSUE TITLE
Weird input behaviour

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/superhero-wallet#1324]
![image](https://user-images.githubusercontent.com/9008074/136743126-46287be8-ed6e-470f-bc01-1d4270b75ce7.png)

_Originally posted by @CedrikNikita in https://github.com/aeternity/superhero-wallet/pull/1301#pullrequestreview-775846714_

![image](https://user-images.githubusercontent.com/9008074/136746450-988e8a75-7a3e-42ab-871f-7b8a0bcc3d0b.png)

**Comment by Liubov-crypto** [comment]
Still reproducible on the current product branch Commit 6ad7d04

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up again.
