### ISSUE TITLE
Wrong link for blockchain explorer after sending tx

### ISSUE THREAD

**Issue by ErkanKanden** [aeternity/superhero-wallet#1342]
![Bildschirmfoto 2021-10-21 um 16 31 45](https://user-images.githubusercontent.com/14875828/138299665-81d845d2-eb76-4a40-9a47-4b80a7451152.png)
Link leads to https://mainnet.aeternal.io/transactions/th_... , but it should be https://explorer.aeternity.io/transactions/th_... I guess

**Comment by CedrikNikita** [comment]
Latest version on the Firefox is now 0.9.6 and it doesn't have such problem.
