### ISSUE TITLE
Option „use as new default“ when setting a pointer to a name

### ISSUE THREAD

**Issue by marc0olo** [aeternity/superhero-wallet#1352]
![image](https://user-images.githubusercontent.com/8124114/138682642-1186eb43-69f1-4411-9d9e-674b760c8213.jpeg)

currently this doesn't seem to be possible.

sidenote:
- generally I am currently having problems updating my name and setting a pointer ("Name Update Succesful") but tx not being processed

**Comment by subhod-i** [comment]
@marc0olo Is this still persist?

**Comment by marc0olo** [comment]
@subhod-i I have no idea - too much time past. I will wait for the redesign of AENS section and then further comment ;-) ... you can close if you want

**Comment by subhod-i** [comment]
@marc0olo I will close this for now. If such issues arise in the future, we can reopen or create a new GH issue. Thanks!
