### ISSUE TITLE
Get rid of duplicate css for urls

### ISSUE THREAD

**Issue by etharner** [aeternity/superhero-wallet#1378]
Either rethink it as a component/mixin or make architectual adjustments.

https://github.com/aeternity/superhero-wallet/blob/954945fb7078fced6467680521eeb9938e984fa7/src/popup/router/pages/Address.vue#L35-L41

https://github.com/aeternity/superhero-wallet/blob/954945fb7078fced6467680521eeb9938e984fa7/src/popup/router/pages/SuccessTip.vue#L150-L153

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up again.
