### ISSUE TITLE
Transactions appear with the delay in the wallet

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#1403]
Transactions appear with the delay in 5 minutes in the wallet. 
I made a transaction at 12:35. The transaction became visible in the wallet only at 12:39.
Details: https://explorer.aeternity.io/transactions/th_2NAkidc9VzaxnDTzpJ77ZpPASMxJ9Dg8CDtJAcgcBxLbo4M9Ge

commit 72f9472/ v.0.9.6

**Comment by kenodressel** [comment]
Will probably be resolved by the middleware team in the next couple of weeks.

**Comment by CedrikNikita** [comment]
Fixed after deployment of [this mdw](https://github.com/aeternity/ae_mdw/releases/tag/v1.15.0) release.
