### ISSUE TITLE
Wrong tokens balance

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#1505]
I had 999900999983786.5 Davidyuk on my balance
I sent 2 Davidyuk to ak_cEjh5on5RvoBw8zqCGS4VWeY2bmNYNPjn3SCZutYyVLWKf7X1 
The balance should be 999900999983784.5 Davidyuk

Tx: https://explorer.aeternity.io/transactions/th_2SC2ib54k1QJEJ5ZNeEUPUsaX1TNm36pdLV6bU1Hs2N7Mq1LkU
https://explorer.aeternity.io/transactions/th_pUJzEmwVPedg3jpWGuw5oXUa5EyGsWv5UFpkdYwyckBTWR4KP
https://explorer.aeternity.io/transactions/th_2qYb2b2AHkTF8ysT5LBGr93mP3bH2B6HgnRefVS6yZjvsqoqRK
https://explorer.aeternity.io/transactions/th_2Z7pjY5sz3RZDH1hWafvC5RWz4gtSa37Nyi98rusLUdzvdVTkA

Reproduced on the development branch.

![dav ](https://user-images.githubusercontent.com/69896204/179496392-315bc7a1-86f6-49bc-b79e-ef241e52430e.png)

**Comment by CedrikNikita** [comment]
depending on https://github.com/aeternity/ae_mdw/pull/777 being released and deployed

**Comment by Liubov-crypto** [comment]
Now this issue again reproducible on the current dev branch https://github.com/aeternity/superhero-wallet/commit/e7028cdb3de7f8bce30922404ec58699f144d4a2
