### ISSUE TITLE
Invalid Date of Transactions

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#1570]
The transactions are displayed with the wrong date on accounts if you do not wait for all DEX transactions to load: 

![ma](https://user-images.githubusercontent.com/69896204/189134860-c421ca21-e82e-4f57-955a-d37fe7b95ed9.png)

This issue is not supposed to be fixed by https://github.com/aeternity/superhero-wallet/pull/1567

**Comment by Liubov-crypto** [comment]
I checked, still reproducible.

**Comment by Liubov-crypto** [comment]
Not reproducible for me on the current dev branch.

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up again.
