### ISSUE TITLE
The top panel is not fixed on overscrolling anymore

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-wallet#1704]
| Now | Before | Overscrolling in iOS settings |
|---|---|---|
| ![RPReplay_Final1668764455](https://user-images.githubusercontent.com/9007851/202674514-f3f68c10-e188-4750-84d8-9f9e985b66b5.gif) | ![RPReplay_Final1668764429](https://user-images.githubusercontent.com/9007851/202674528-f70d55d2-980a-4464-b9f8-dee1438c9e50.gif) | ![RPReplay_Final1668764565](https://user-images.githubusercontent.com/9007851/202674492-cd050dc7-2df5-451d-aabb-bcdbf78bf9b6.gif) |

v1.0.1 compared with https://feature-clean-up-global-styles.wallet.z52da5wt.xyz/

**Comment by Liubov-crypto** [comment]
Not reproducible for me on product, commit 61e54cd. Can be closed.
