### ISSUE TITLE
Main screen is not scrollable in iOS Cordova on 1.0.1 after opening a modal

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-wallet#1705]
release 1.0.1 on commit e7896b96791d820a703dfd6d301faef9af78deeb I have no good way to reproduce it, but it happened already two times to me on a physical iPhone XS. Probably it is related to closing some popup.

https://user-images.githubusercontent.com/9007851/202681161-35a8a093-931a-4afd-ae87-ede6a63d633d.mp4

**Comment by Liubov-crypto** [comment]
I can't reproduce this bug on iPhone 13.

**Comment by Liubov-crypto** [comment]
Not reproducible for me on https://github.com/aeternity/superhero-wallet/pull/2208

**Comment by Liubov-crypto** [comment]
Not reproducible for me on product, commit 61e54cd. Can be closed.
