### ISSUE TITLE
Removing permission breaks wallet for URL

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/superhero-wallet#1726]
I've reported this error https://www.youtube.com/watch?v=1sBbrp4LRWA in devchat already and could narrow it down, I think @subhod-i made similar findings but I don't remember exactly anymore, thought I'd create an issue though.

1. load dAepp with Sh wallet integration
2. Accept/Grant permissions
3. Go to permission settings, remove permission for site
4. reload site and accept permissions
5. RPC error as if user would have denied permissions.

This can only be fixed by a full wallet reset (confirmed) or maybe manually adding permissions for that site again (could not test, as URL validation bug currently prevents adding localhost 😜)

**Comment by subhod-i** [comment]
Totally related to the one we already discussed. Hopefully tackled in the same ticket.

**Comment by subhod-i** [comment]
@ifaouibadi is working on this.
