### ISSUE TITLE
Adjust current transaction displaying

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/superhero-wallet#1809]
- [x] All the fungible tokens you received are displaying incorrectly (as a transactions for a different account)
- [ ] transactions user have sent to himself are shown with a plus, which is incorrect sinse he spend money on fee and got nothing in return

**Comment by Liubov-crypto** [comment]
Reproducible for me on develop branch: 
![вум](https://user-images.githubusercontent.com/69896204/221191853-60ea6ad4-5a35-4e1a-9e5e-e9a60a0dd824.png)
