### ISSUE TITLE
Redirect/no redirect tests running too slow

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-wallet#196]
https://travis-ci.com/github/aeternity/superhero-wallet/builds/161850958#L1157-L1171
So, 15 tests running about 6 seconds/test, I think it is too long for redirect testing and it was running faster as I remember. Can it be covered by unit tests?

**Comment by vmangelovv** [comment]
there are .wait(2000) added between every visit command.
It looks like it cannot visit that fast, that is why is used the wait.

**Comment by davidyuk** [comment]
> there are .wait(2000) added between every visit command.
> It looks like it cannot visit that fast, that is why is used the wait.

> In Cypress, you almost never need to use cy.wait() for an arbitrary amount of time. If you are finding yourself doing this, there is likely a much simpler way.

https://docs.cypress.io/guides/references/best-practices.html#Unnecessary-Waiting
