### ISSUE TITLE
Wallet shouldn't be openable over http

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-wallet#1979]
**Describe the bug**
Currently, Superhero Wallet can be opened over http. In this case MITM can replace JS payload exposing sensitive data to third parties. Also, some modern web APIs is not working in unsecured contexts that may produce unexpected errors.

**To Reproduce**
1. Open "http://wallet.superhero.com" in Chrome

**Expected behavior**
Web server should constantly redirect HTTP requests to HTTPS. With no ability to open the wallet over HTTP.

**Screenshots**
<img width="811" alt="Screenshot 2023-04-09 at 10 27 30" src="https://user-images.githubusercontent.com/9007851/230752574-eda87e78-1439-4994-a534-3965117a8dc7.png">

**Comment by mmpetarpeshev** [comment]
Its deployed on gh pages and required to enable the https redirect in the configuration.
