### ISSUE TITLE
Signer preview not visible on non-maximized window

### ISSUE THREAD

**Issue by ErkanKanden** [aeternity/superhero-wallet#2022]
Firefox browser plugin, version 1.1.0.
![Bildschirmfoto 2023-04-24 um 13 32 44](https://user-images.githubusercontent.com/14875828/233984555-426bf28a-eba4-4e2a-a1c9-8b7cc8bcfdfe.png)

When clicking on the signer's field, I can select from my wallet addresses to choose a signer, but it's not visible nor clickable on a non-maximized browser window (this case was on Firefox). I had to maximize the window and upon clicking on the SH wallet plugin again, I had to restart the journey from the SH wallet dashboard. I would say to prevent this bad UX, the signer thumbnail should be optimized for non-maximized window sizes.

**Comment by Liubov-crypto** [comment]
Also, not reproducible for me with FF plugin.

**Comment by Liubov-crypto** [comment]
Not reproducible for me on the latest dev branch.

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up again.
