### ISSUE TITLE
Can't create multisig from Firefox plugin

### ISSUE THREAD

**Issue by ErkanKanden** [aeternity/superhero-wallet#2023]
Firefox browser plugin, version 1.1.0.
![Bildschirmfoto 2023-04-24 um 14 10 50](https://user-images.githubusercontent.com/14875828/233992793-42831d6e-ab8c-4a6c-90a4-4173f3fe0875.png)

Both signer accounts are from the same superhero wallet seed hash, was trying it just for testing. Both accounts are funded with at least 1 AE, but when clicking on the blue button nothing happens. 

PS: The same methodology worked on Google Chrome, so it has to be a Firefox-specific bug.

**Comment by Liubov-crypto** [comment]
Tried in FF extension with 2 accounts from the same wallet, not reproducible for me: 

https://user-images.githubusercontent.com/69896204/234007016-c189d5d1-3efe-4a4c-842c-f3326bff5230.mov

**Comment by ErkanKanden** [comment]
I just discovered that the same issue happens when choosing one of my accounts that Is already associated with a .chain name in the SH wallet UI. I select one of my accounts with a .chain name showing automatically for signer 1, and I cannot create a multisig vault even if I use the full public wallet address for signer 2 account.
