### ISSUE TITLE
onAddressChange not triggered in active aepp <-> wallet connection

### ISSUE THREAD

**Issue by marc0olo** [aeternity/superhero-wallet#2198]
see https://github.com/aeternity/aepp-boilerplate-react/issues/6#issuecomment-1642399461

confirmed by @CedrikNikita.

is this already fixed and just awaiting new release?

**Comment by subhod-i** [comment]
This has been fixed in the develop. New release shall fix this.

**Comment by CedrikNikita** [comment]
fixed #2209
