### ISSUE TITLE
Mobile share functionality

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-wallet#260]

**Comment by davidyuk** [comment]
![Screenshot 2020-05-13 at 17 50 38](https://user-images.githubusercontent.com/9007851/81786211-b7aa6880-9542-11ea-81ec-bba9a0a364d3.png)

Is it ok to have the wallet in the list of applications or needed to have a special action like "Tip with Superhero"? I'm not sure that [the plugin](https://github.com/j3k0/cordova-plugin-openwith) that I'm planning to use is capable of the second option. Also, it shouldn't be difficult to implement the first option on Android.

**Comment by mradkov** [comment]
> ![Screenshot 2020-05-13 at 17 50 38](https://user-images.githubusercontent.com/9007851/81786211-b7aa6880-9542-11ea-81ec-bba9a0a364d3.png)
> 
> Is it ok to have the wallet in the list of applications or needed to have a special action like "Tip with Superhero"? I'm not sure that [the plugin](https://github.com/j3k0/cordova-plugin-openwith) that I'm planning to use is capable of the second option. Also, it shouldn't be difficult to implement the first option on Android.

Sure!
