### ISSUE TITLE
Currency dropdown z-index issue

### ISSUE THREAD

**Issue by venimus** [aeternity/superhero-wallet#263]
![image](https://user-images.githubusercontent.com/632282/80984835-0f581e00-8e37-11ea-9fbb-b3f37fffaad8.png)

**Comment by vmangelovv** [comment]
which browser do you use? Because I tested it in chrome and firefox and it looks good.

**Comment by venimus** [comment]
This was reported from users. It appears fixed as I also had it some time ago and now 0.26 it is ok. I guess can be closed
