### ISSUE TITLE
Tx between 2 accounts from the same wallet is visualized in a wrong way on tx details screen.

### ISSUE THREAD

**Issue by smaroudasunicorn** [aeternity/superhero-wallet#2817]

**Comment by onvisions** [comment]
**Bug:** There is a bug in visualization of the SpendIn/SpendOut transactions when they are between accounts belonging to the same wallet. 
Currently if the user sends AE from account 1 to account 2 and then visits the transaction details page (first from account 1, then from account 2) they will see exactly the same visualization on top. Both transactions are incorrectly labeled "Spend Out" although one is "Spend In". 

See the recording for example of 3.2 AE transfer:

https://github.com/superhero-com/superhero-wallet/assets/12225410/f7eea1fe-9955-4d00-8c58-a7de6ceb2810

**Fix:** 

Correct visualization from æternity account 1:

![Image](https://github.com/superhero-com/superhero-wallet/assets/12225410/1277106b-fea3-47be-83c1-94446ea4abef)

**Comment by Liubov-crypto** [comment]
Fixed on dev branch, can be closed: 


https://github.com/superhero-com/superhero-wallet/assets/69896204/cd626aa5-1bd4-4a0d-a536-bd7e0594b94e
