### ISSUE TITLE
Connecting to testnet shows error

### ISSUE THREAD

**Issue by thepiwo** [aeternity/superhero-wallet#294]

**Comment by thepiwo** [comment]
I think the change network feature is incomplete without setting the superhero contract address + superhero backend address. Has this been tested when implementing?

**Comment by mradkov** [comment]
I think we needed to make a decision whether to add additional config for superhero for different networks (e.g. tip contract address, backend/payfortx service etc.).

Or warn people they are not running on mainnet and superhero will not work for them and disable the tipping and claiming functionalities for there.
