### ISSUE TITLE
Can't connect to wallet later than 5? seconds after opening

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-wallet#295]
**Describe the bug**
It seems that the wallet tries to connect to aepp only in the first five seconds. It blocking use cases when connection established later than five seconds after opening. For example, it may be needed in dapps that supports several blockchains. Or in my case, I wanted to put all staff in a simple click handler without initialization of sdk after page opening.

**To Reproduce**
1. Run https://github.com/aeternity/jwt-auth/tree/reproduction-dont-init-sdk-immediately
2. Press "Join meeting with aeternity account" after 5 seconds
3. Ensure that it not works

**Expected behavior**
To be able to connect to the wallet at any time.

**Additional context**
Related issue: https://github.com/aeternity/aepp-sdk-js/issues/907

**Comment by petbaik** [comment]
If we use `setInterval` here https://github.com/aeternity/superhero-wallet/blob/develop/src/lib/rpcWallet.js#L279 maybe it will solve the problem ?

**Comment by mradkov** [comment]
> If we use `setInterval` here https://github.com/aeternity/superhero-wallet/blob/develop/src/lib/rpcWallet.js#L279 maybe it will solve the problem ?

Can you try this?

**Comment by petbaik** [comment]
> > If we use `setInterval` here https://github.com/aeternity/superhero-wallet/blob/develop/src/lib/rpcWallet.js#L279 maybe it will solve the problem ?
> 
> Can you try this?
It worked. Also think this is the case with connection problems to wallet in jelly swap app
