### ISSUE TITLE
Transaction.vue: Transaction list filtered by received is empty

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/superhero-wallet#336]
![image](https://user-images.githubusercontent.com/9008074/83378710-e4082500-a41c-11ea-895d-4a2b290ce935.png)
As a user I expect that every transaction that gives me AEs should be in received and every actual topups should be in topups.

**Comment by petbaik** [comment]
Hey, actually currently this filter is for received tips and it looks like your address has no received tips https://raendom-backend.z52da5wt.xyz/cache/events/?address=ak_2AVeRypSdS4ZosdKWW1C4avWU4eeC2Yq7oP7guBGy8jkxdYVUy&event=TipWithdrawn
