### ISSUE TITLE
Fix styles linter path 

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-wallet#341]
https://github.com/aeternity/superhero-wallet/blob/1e14c0b380e60bcbdb961e8568695610c8dd0410/package.json#L10

I have a built css file (that rises a lot of issues because it is minified). I see these issues when the file is in `dist` folder, but I don't see them if it is in `dist/web/root`.
- linter shouldn't lint files in `dist` folder
- is linter properly finds files in nested directories?

**Comment by CedrikNikita** [comment]
For me it's checking all the nested files in the `dist` folder. Like `dist/web/root/popup.css` and so on.
