### ISSUE TITLE
Can't retip with the current develop version

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-wallet#345]
**To Reproduce**
1. Go to 'https://develop.aggregator.z52da5wt.xyz/tip/26'
2. Retip
3. See "Unsupported network" error

Also, I have tried the latest version from master (0.1.2) and it works ok.

**Comment by mradkov** [comment]
I cannot reproduce this. Just re tipped.

**Comment by davidyuk** [comment]
Probably something got changed, it works now.
