### ISSUE TITLE
Confirm screen overlaps with status bar on iOS

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-wallet#361]
<img src="https://user-images.githubusercontent.com/9007851/84264032-d9a80280-ab63-11ea-825d-57f39448c84a.png" width="50%" />

**Comment by davidyuk** [comment]
The same issue was reported in the telegram group:

<img src="https://user-images.githubusercontent.com/9007851/108835876-26901400-75e1-11eb-92b4-a5687cfbbd7e.jpg" width="50%" />

**Comment by imollov** [comment]
fixed in #969
