### ISSUE TITLE
Make wallet to use forwarding with url param

### ISSUE THREAD

**Issue by shapkarin** [aeternity/superhero-wallet#378]
Hello. Maybe it will be nice if wallet can read url param like `callback` and forward user to that callback after user retrieve or create new account.
The reason why I think we need that is because when you want to use deeplinks and web wallet to to get the JWT token:
1. first you need to "auth" with web wallet
2. after you "auth" it's forward user to the http://wallet.superhero.com
3. And user see http://wallet.superhero.com instead of `share account page`

I hope it's clear. Please, notice me if I'm wrong or something is not clear.

**Comment by shapkarin** [comment]
I'm wrong a little at point 3. We need to forward not to the jitsi client or superhero but the url was defined as a `callback`.

**Comment by mradkov** [comment]
https://github.com/aeternity/superhero-wallet/blob/26020376989317d32f6d2fbd954d3514e13a6432/tests/pages/index.html#L44-L50

**Comment by shapkarin** [comment]
@mradkov I'm about the different - before we call address method.
