### ISSUE TITLE
Cannot re-initialize wallet 

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/superhero-wallet#383]
Using [this](https://github.com/kenodressel/aepp-boilerplate/blob/master/src/utils/aeternity.js) Vue.js boilerplate from @kenodressel and @thepiwo , I can successfully get the wallet initialized. 

My UI has a switch to overwrite the main reference to the wallet with a "web-wallet", SDK with hardcoded keys, which also works. 

But if I want to initialize the superhero wallet again with the same function as before, the issue pops up here: https://github.com/kenodressel/aepp-boilerplate/blob/master/src/utils/aeternity.js#L135 : `newWallet` is not defined. If I use a pattern I found cached somewhere [on the web](https://webcache.googleusercontent.com/search?q=cache:mdUgQwAwG_oJ:https://gitmemory.com/davidyuk+&cd=18&hl=en&ct=clnk&gl=de) by @davidyuk , using some of the `wallets` if the `newWallet` is undefined, I get the following error: 

```
core.js:6189 ERROR Error: Uncaught (in promise): TypeError: i.connect is not a function
TypeError: i.connect is not a function
    at Object.init (aepp-sdk.browser.js:8)
    at Stamp (index.js:34)
    at aepp-sdk.browser.js:8
    at s (aepp-sdk.browser.js:8)
    at Generator._invoke (aepp-sdk.browser.js:8)
    at Generator.forEach.t.<computed> [as next] (aepp-sdk.browser.js:8)
    at n (aepp-sdk.browser.js:1)
    at c (aepp-sdk.browser.js:1)
    at aepp-sdk.browser.js:1
```

when doing 
```
const wallet = newWallet || Object.values(wallets)[0];
```
instead of just always using `newWallet` which is undefined on the second initialisation run. It also doesn't help to store `newWallet` somewhere else like this:

```
var cachedWallet;

 const handleWallets = async ({ wallets, newWallet }) => {
    detector.stopScan();
    newWallet ? cachedWallet = newWallet : true;
    const walletConnection = newWallet ? await newWallet.getConnection() : cachedWallet.getConnection()
```

**Comment by thepiwo** [comment]
Is this an issue with the boilerplate itself or rather underlaying sdk?

**Comment by nikita-fuchs** [comment]
I wish I could tell already. I'm not fully familiar with the logic of the wallet integration, but I think @nduchak has an idea maybe?

**Comment by nikita-fuchs** [comment]
You can reproduce here: https://github.com/aeternity/fire-editor/tree/superhero_wallet_impl just start, click the big switch once to activate wallet extension(wait a little), then again to activate web (wait a little again), then try activating wallet back and check the errors.

**Comment by thepiwo** [comment]
so when I try it out:
1.  static client initialized
2. detect wallet -> newWallet is the detected wallet
3. switch to static client
4. detect wallet -> wallet includes the previously detected wallet and newWallet is empty as it's not new

works for me as expected when I don't forcefully reuse newWallet
example: https://github.com/kenodressel/aepp-boilerplate/compare/switch-wallets-example#diff-ab528ff1d3f8ddbc9c5a5c04cfea2186R148

**Comment by nikita-fuchs** [comment]
Weehoo, for some reason it works now, maybbe I made a mistake somewhere referencing the existing wallet. It's strange though, because I used to store `newWallet` and use it when it was not defined in that function, the same way as you basically do here in that code. Must have had some ref mistake or whatever. anyways, thanks for the help !

**Comment by thepiwo** [comment]
In this code I don't store `newWallet`, just it's id, to reference its later when passed in `wallets`, we can't store the wallet itself as it contains functions I assume
