### ISSUE TITLE
User invites referal

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-wallet#390]
Add new view for generating invite inks.

User should be able to generate an invite link with or without an attributed balance.
You may choose to share this link with another individual (so we should keep track of those).

There should be an overview for you to see which invite links you generated and how much balance they have. You can claim the balance back or top it up additionally, before they are claimed.

---

Invite link should be created by:
- generating a new seed (keypair) for this link
- (optional) allow user to top it up with a balance (`spendTx` to it)
    - the `spendTx` should contain a payload `referral`
- base58 encode so it can be shared (eg. `https://superhero.com/i/{BASE_58_encoded_invite_privkey}`) which would be later deep-linked from superhero UI

Opening such link (deeplink)
- open a new view which will decode the url - and claim the balance to your account

Invite links view
- should have a section to keep track of the generated links and the remaining balances
- should have a button to claim the balance back (which would make a spendtx from that keypair back to your main account)

**Comment by mradkov** [comment]
I think the deeplink should be implemented last. cc @davidyuk

**Comment by davidyuk** [comment]
The issue is closed, but I didn't implement any deeplinks. Is it still actual? How superhero-ui should handle invite link?

**Comment by mradkov** [comment]
> The issue is closed, but I didn't implement any deeplinks. Is it still actual? How superhero-ui should handle invite link?

Resolving the link is implemented with `wallet.superhero.com`. (just to have it in history)
