### ISSUE TITLE
Fix tipping contract on testnet

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-wallet#4]
Running on testnet I have an error:
```
Error: Contract with address ct_2AfnEfCSZCTEkxL5Yoi4Yfq6fF7YapHRaFKDJK3THMXMBspp5z not found on-chain or not active
```
Probably this address is wrong or outdated
https://github.com/aeternity/superhero-wallet/blob/e1c2ebb5918704401b04193bf4be2391f310d384/src/popup/utils/constants.js#L103

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up in next versions.
