### ISSUE TITLE
Twitter tip button uses wrong URL

### ISSUE THREAD

**Issue by marc0olo** [aeternity/superhero-wallet#411]
**Describe the bug**
When using the tip button for a tweet the button uses an URL for one of the links that are included at the bottom of the tweet, e.g. `/likes` or `/analytics`. Instead it should use the URL of the tweet. Not the likes, analytics or whatever else.

In my case I didn't check the URL and was logged in. I tipped 1 AE to an URL that isn't publicly visible and therefore not claimable.

This is the tip:
- https://superhero.com/tip/1534

**Comment by mradkov** [comment]
Thanks for noticing and reporting this!
