### ISSUE TITLE
Logger ignores exceptions shown in vue event handlers

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-wallet#437]
Check this reproduction: 8365df63bed7c04849f324a9ec282a8f8db76752

https://reproduction-logger.wallet.z52da5wt.xyz/

I assume that the button on click should show a modal proposing to send the exception to us.

**Comment by mradkov** [comment]
> I assume that the button on click should show a modal proposing to send the exception to us.

Yes, this is the intended behavior.
