### ISSUE TITLE
Generating an invite link problem

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-wallet#457]
Generating an invite link is broken

<img width="968" alt="Screenshot 2020-08-10 at 15 44 06" src="https://user-images.githubusercontent.com/13139371/89783957-7f55fe80-db20-11ea-99a8-7beadd7cde6d.png">

**Comment by davidyuk** [comment]
Before releasing the invite links I have renamed `date` to `createdAt` in #438 without store migration. Maybe this exception is because of the state of an outdated version?
