### ISSUE TITLE
"Your names" shows many names which are not mine

### ISSUE THREAD

**Issue by databu** [aeternity/superhero-wallet#469]
The "Your names" view shows many names which are not mine. The list is very long, possibly it's showing all aens names. Also, the automatically chosen default name is not mine. See attached screenshot. This is in the Firefox extension.

**To Reproduce**
In the Firefox Superhero extension, connect an account.
Then go to menu -> Names 
The "Your names" tab should be shown, review the list of names.

**Expected behavior**
Only my own claimed names (for address ak_HvyZuarbg54JTmq4zNU7QxoTPhKzdBisjbTEu72gCQx7GGt1R) should be shown, and a default chosen from them.

**Screenshots**
<img width="179" alt="Monosnap_2020-08-16_18-13-15" src="https://user-images.githubusercontent.com/1074007/90337727-0efe2000-dfed-11ea-8e90-d0b69f580052.png">

**Desktop (please complete the following information):**
Firefox 79.0 (64-bit) on macOS 10.14.6
Superhero extension 0.2.4 updated on 27 June 2020

**Comment by mradkov** [comment]
Can you try updating to the latest `0.3.2` version of superhero wallet and see if the issue is still reproduceable?

**Comment by baltar** [comment]
Yes, the problem is still there with 0.3.2

**Comment by mradkov** [comment]
The problem can be corrupt data coming from the old middleware. It will be resolved as soon as we integrate the new one.

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up in next versions.
