### ISSUE TITLE
Register .chain name

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#477]
Hello team! 

I tried to register a new .chain name but something went wrong. I sent a report via SH wallet (Superhero 2f652fc / v.0.2.4. extension for Chrome). Here is a screenshot: 
![Знімок екрана 2020-08-18 о 4 05 02 пп](https://user-images.githubusercontent.com/69896204/90614654-a349cc00-e213-11ea-8b30-889fd37a52e1.png)

Thank you in advance!

**Comment by davidyuk** [comment]
@mradkov how can I check these reports?

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problem. Feel free to reopen this issue, if it will pop up in next versions.
