### ISSUE TITLE
Unable to connect to testnet

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/superhero-wallet#480]
While calling getNameEntryByName (name), GET to https://sdk-testnet.aepps.com/v2/names/superhero.chain failed with 404: Name not found

**Comment by mradkov** [comment]
Not sure if the old middleware is resolving the names correctly. Other than that - does`superhero.chain` exist on testnet?

**Comment by davidyuk** [comment]
```
~ curl https://testnet.aeternity.io/v2/names/superhero.chain
{"reason":"Name not found"}
```

It doesn't look so.

**Comment by davidyuk** [comment]
is it resolved somehow?
