### ISSUE TITLE
Bugs on feed

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#484]
Hello Team! 

I tested the Superhero Tip button on Youtube and tried to claim tokens after. But I did not see these tokens in my wallet in the Received section. Although there were no problems with the claiming. 
Data on mainnet:  https://mainnet.aeternal.io/transactions/th_2GJeQEsLxPpGUcErngc3eF8hQtGafd54ANyPTgAhAdKvZuLmRS

There are also bugs in the Superhero.com feed, not all data are visible. 

![Знімок екрана 2020-08-25 о 2 23 52 пп](https://user-images.githubusercontent.com/69896204/91175786-fc20d500-e6e9-11ea-8174-b1edba9ecdf9.png)

![Знімок екрана 2020-08-25 о 2 34 49 пп](https://user-images.githubusercontent.com/69896204/91175965-43a76100-e6ea-11ea-9388-ec236974a175.png)

https://superhero.com/tip/1808

and some design bugs in the wallet. When I enter 0.1 æ in the amount field, the field changes colour to red (the signal that something is wrong), although 0.1 æ is sufficient for a test tip.

![Знімок екрана 2020-08-25 о 1 38 42 пп](https://user-images.githubusercontent.com/69896204/91176496-07283500-e6eb-11ea-9266-b99d3afa6406.png)

I used the Superhero wallet ver. c7cb8cc / v.0.3.2 for Firefox. 
Browser: Firefox Ver.77 for Mac.

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up in next versions.
