### ISSUE TITLE
Go Back Button doesn't work on Jitsi Meet 

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#489]
Hello team! 

I tested Jitsi Meet and tipping during the meeting. 
The "Go back" button in the wallet does not work correctly (it is not active from time to time):

![Знімок екрана 2020-08-28 о 12 49 36 пп](https://user-images.githubusercontent.com/69896204/91564085-bb72c700-e948-11ea-9ebf-ae8f4213fab4.png)

I tested SH wallet 9302621 / v.0.3.2 on Chrome, Firefox and Brave browsers.

**Comment by venimus** [comment]
It is actually going "back" in the jitsi's iframe history

**Comment by mradkov** [comment]
> It is actually going "back" in the jitsi's iframe history

Probably a problem with cross-iframe navigation.

**Comment by mradkov** [comment]
Should be fixed in 0.3.3. @venimus can you try the release branch and confirm if everything is ok.

**Comment by etharner** [comment]
@mradkov Can we close this if it's fixed? As I remember this problem was on 0.3.2 but not on 0.3.3

**Comment by Liubov-crypto** [comment]
Tested, works on my side. This issue can be closed.

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problem. Feel free to reopen this issue, if it will pop up in next versions.
