### ISSUE TITLE
Mainnet view on SH Web wallet (UX/UI) 

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#493]
I tried to check the transaction on my web wallet and was redirected to the mainnet directly in my wallet view. But now, I don't know how to return to my wallet? 
I logged with Web wallet and want to join Jitsi Meet via the invite link.

My steps:
1. Click on invite Link: https://superhero.com/meet/AdequateMarriagesCorrectEqually
2. Click on Join meeting
3. Redirect to the Room
4. Choose random message
5. Click on Tip Button (Blue Diamant)
6. Enter amount. The amount should be >0.1 ae token
7. Click on Tip
8. Click on Confirm on Pop up
9. Check transaction on superhero.com feed or https://mainnet.aeternal.io/transactions/
10. Click on "eye" on my wallet

![Знімок екрана 2020-09-03 о 2 18 21 пп](https://user-images.githubusercontent.com/69896204/92110133-ed75a480-edf2-11ea-8c4c-abc6622c9ce1.png)

I think that the user will be confused if there no option to return in the wallet. I have not seen such a button.
￼
* OS: Mac OS 10.13.6
* Browser: chrome
* Version: 85.0.4183.83

P.S. User should use Go back button on the browser to return the previous view on the wallet.

![Знімок екрана 2020-09-03 о 2 38 37 пп](https://user-images.githubusercontent.com/69896204/92110404-50673b80-edf3-11ea-96d6-6eb21db3873f.png)

**Comment by mradkov** [comment]
I cannot reproduce this on the standalone web wallet nor by using the extension or mobile app. The problem only exists in the iframed wallet on superhero.
