### ISSUE TITLE
Issues with Safari, Brave and Firefox login with iframe wallet 

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#496]
After logging in with the iframe wallet it is impossible to enter the Jitsi room. Pop-ups do not appear, the acceptance of which is a necessary entry condition. Instead, endless loading of the pre-join page:

<img width="1666" alt="Wire 2020-09-08 at 08-08-04" src="https://user-images.githubusercontent.com/69896204/92451347-42376780-f1c5-11ea-8f32-3db578b7164f.png">

<img width="1673" alt="Wire 2020-09-08 at 08-08-13" src="https://user-images.githubusercontent.com/69896204/92451372-482d4880-f1c5-11ea-8e6f-ad186dbe08a6.png">

<img width="1678" alt="Wire 2020-09-08 at 08-11-50" src="https://user-images.githubusercontent.com/69896204/92451393-4e232980-f1c5-11ea-9ba1-3bc359a8c981.png">

<img width="1679" alt="Wire 2020-09-08 at 08-11-56" src="https://user-images.githubusercontent.com/69896204/92451421-554a3780-f1c5-11ea-9949-a2f70cd21ae4.png">

Steps to reproduce the behaviour:
1. Go to superhero.com. Login with iframe wallet.
2.  Go to superhero.com/meet. Click on Go button. (After clicking on the Go button, a pop-up window should appear allowing you to redirect the user to the pre-join page. Pop-up does not appear) 
3. See error: endless loading of the pre-join page

 - Browser:  Firefox, Safari, Brave.

**Comment by Liubov-crypto** [comment]
chrome/firefox/brave + iframe wallet:
I enabled pop-ups in chrome/firefox/brave browsers, but it still doesn't work.
I cleared the cache and cookies, but the pop -up does not appear.
There is an interesting thing if I click on the eye to check transactions on the mainnet (mainnet info appears in the wallet view), and then click back in the browser, then the pop-up appears.

https://youtu.be/h0aqs8_emtM

**Comment by Liubov-crypto** [comment]
Login with iframe wallet works:

Go to superhero.com/meet
Click on Go button
Login with iframe wallet
Click on Accept Pop up

(In chrome/firefox  pop-ups  appears 2 times, in Brave only 1 time)

Login with iframe wallet doesn’t work:

Go to superhero.com/meet
Login with iframe wallet or you are already logged in
Click on Go button
Wait when the pop-up appears
Error: no pop-up

**Comment by davidyuk** [comment]
is ti the same issues is https://github.com/aeternity/jitsi-meet/issues/240 ?

**Comment by Liubov-crypto** [comment]
After login to iframe wallet on Safari browser appears such pop-up: 
<img width="1597" alt="Wire 2020-10-06 at 6_27 PM" src="https://user-images.githubusercontent.com/69896204/95224169-0e228700-0803-11eb-9556-20fd7e440b9c.png">

**Comment by davidyuk** [comment]
<img width="907" alt="Screenshot 2020-10-07 at 06 55 45" src="https://user-images.githubusercontent.com/9007851/95285709-2083db80-086a-11eb-9d10-f8f1bf61f8d1.png">
to fix this, currently, we need to uncheck "Prevent cross-site tracking" option in Safari's preferences

**Comment by Liubov-crypto** [comment]
The issue that Safari does not see the iframe wallet happens in Safari browsers below version 0.14. 
I used:
OS: MacOS High Sierra 10.13.6
Safari: ver. 13.1.2 (13609.3.5.1.5)
Maybe we should include a warning that users should use version 0.14 or higher.
![Знімок екрана 2020-10-07 о 2 06 01 пп](https://user-images.githubusercontent.com/69896204/95324760-e554cd00-08a8-11eb-928b-34c3f0b9b91d.png)

![Знімок екрана 2020-10-07 о 2 08 00 пп](https://user-images.githubusercontent.com/69896204/95324778-ec7bdb00-08a8-11eb-8b99-48ff5f83af34.png)
![Знімок екрана 2020-10-07 о 2 08 11 пп](https://user-images.githubusercontent.com/69896204/95324784-eede3500-08a8-11eb-9b49-cc309c61cf1b.png)
![Знімок екрана 2020-10-07 о 2 08 18 пп](https://user-images.githubusercontent.com/69896204/95324792-f0a7f880-08a8-11eb-95f8-5cab44c03b4f.png)

**Comment by Liubov-crypto** [comment]
Tested, works on my side. This issue can be closed.

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problem. Feel free to reopen this issue, if it will pop up in next versions.
