### ISSUE TITLE
UX / UI suggestion for "agree to the terms" button in the wallet

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#497]
UX/UI proposal: I propose to make the field where the user agrees to the wallet terms more visible (highlight). Because it is hard to see this field against this background:

![Знімок екрана 2020-09-07 о 4 45 34 пп](https://user-images.githubusercontent.com/69896204/92457439-e40e8280-f1cc-11ea-8d02-6270c36cbfca.png)

**Comment by CedrikNikita** [comment]
Can you provide needed help here? @onvisions

**Comment by onvisions** [comment]
Yes. Change the background of the checkbox (when not selected) to #272831.

**Comment by mradkov** [comment]
This is fixed in #502
