### ISSUE TITLE
Configurable popup messages

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-wallet#506]
Allow users to select whether they want to confirm popups for signing messages and transactions.

This should be part of the settings menu.

The user should be presented with several checkboxes:
- Ask for login requests (on/off)
- Ask for message signing confirmations (on/off)
- Ask for transactions confirmations (on/off)

All of those should respectively do the action after their name. If those are toggled off the confirmation popups should be automatically confirmed for the user without showing up.

related to #492

**Comment by CedrikNikita** [comment]
I do not agree with the third point, it is to risky for the user. I prefer this option as `do not ask permission to sign a transaction up to ...AE` and maybe a slider, or as credit cards have a max ammout.

**Comment by etharner** [comment]
@mradkov Can I add that before making PR?

**Comment by mradkov** [comment]
> I do not agree with the third point, it is to risky for the user. I prefer this option `do not ask permission to sign a transaction up to ...AE` and maybe a slider, or as credit cards have a max ammout.

I agree with you that it is too risky. I also agree with the slider and amount config.

**Comment by mradkov** [comment]
> @mradkov Can I add that before making PR?

Yes, sure!

**Comment by CedrikNikita** [comment]
Even after that, there could be sites that in loop just asking for 1 AE, every millisecond or so. At some point he may lose a lot of money (to a scam site), and may think that the wallet itself made it. There should be a modal warning with a message that you are doing it at your own peril and risk

**Comment by mradkov** [comment]
> Even after that, there could be sites that in loop just asking for 1 AE, every millisecond or so. At some point he may lose a lot of money (to a scam site), and may think that the wallet itself made it. There should be a modal warning with a message that you are doing it at your own peril and risk.

The user will be setting up this configuration on their own risk. If they do not turn this on - they won't open the possibility for such an attack.

The intention and desired outcome of the feature is to put this compromise of `UX/security` under the user's control.
