### ISSUE TITLE
Connecting wallet to Jelly Swap

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#508]
I can’t connect the wallet to the Jelly Swap page: https://app.jelly.market/swap

1. Click on Top Up button on the wallet
2. Click on Swap Crypto for ae tokens
3. Redirection to Jelly Swap
4. Click on SH icon to connect your wallet
5. Error: The icon - do not respond

 - OS:  iOS
 - Browser: chrome, firefox, brave
 - Version: v.0.3.3.
- App for Android ver.0.3.2

Although connecting wallets for other cryptocurrencies work.

**Comment by Liubov-crypto** [comment]
Checked, connection to Jelly Swap works. 
Superhero 4361212 / v.0.5.6

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up again.
