### ISSUE TITLE
Check webpack build procedure

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-wallet#51]
The build is producing 4 items now:
- firefox
- chrome
- aepp
- extension

What is the intended behavour here?

cc @petbaik  @davidyuk

**Comment by petbaik** [comment]
I am using `aepp` and `extension` folders in integration tests

**Comment by mradkov** [comment]
Closing the issue then.

**Comment by davidyuk** [comment]
actually, there is also a build for Cordova 🙂
