### ISSUE TITLE
Visual inconsistences: Main screen

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-wallet#513]
![9edafd79306579ede242ef82766ff0d2384f1490](https://user-images.githubusercontent.com/13139371/93186161-f8abc700-f746-11ea-8ef5-0ac548990941.png)

**Comment by stanislav-slavov** [comment]
These issues would be addressed in the fungible tokens PR. 
It would be better if we introduce design changes separate from introducing new features.

**Comment by davidyuk** [comment]
> It would be better if we introduce design changes separate from introducing new features

I agree, why don't do it this way?

**Comment by stanislav-slavov** [comment]
It is already implemented(except for the ordering) and waiting in https://github.com/aeternity/superhero-wallet/pull/519

**Comment by davidyuk** [comment]
Please, don't bind several features in a single PR, if you have it ready, let's merge it.
