### ISSUE TITLE
Cannot login in superhero.com with 0.3.3

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#520]
superhero.com for some reason does not show my profile if I login with the extension. I meet this on chrome, firefox and brave.

1. Go to superhero.com
2. Login with extension
3. See error: no profile page on superhero.com

The same: 
1. Go to superhero.com/meet
2. Login with extension
3. See error: no profile page on superhero.com

 - OS: iOS
 - Browser: chrome, brave, firefox
 - Version 0.3.3

![Знімок екрана 2020-09-17 о 2 58 54 пп](https://user-images.githubusercontent.com/69896204/93476732-c941b980-f902-11ea-97ec-a5f8bfc756e9.png)

**Comment by mradkov** [comment]
Thanks for the report, I was able to reproduce this. I think its something with the RPC communication.
