### ISSUE TITLE
New wallet generation process hung after deleting an existing account 

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#523]
The wallet hung and did not allow me to create a new account after I left the old one.

Extension on Chrome, Firefox. 

Steps to reproduce the behaviour:
1. Log out from extension.
2. Open extension
3. Click on 'I agree"
4. Click on Generate new wallet
5. Click on Proceed to your wallet
6. See an error on Pop-up:

![Знімок екрана 2020-09-18 о 7 50 13 пп](https://user-images.githubusercontent.com/69896204/93624427-ff596900-f9e8-11ea-8465-092deb773f07.png)

 - OS:  iOS
 - Browser: chrome, firefox
 - Version: 0.3.3

**Comment by Liubov-crypto** [comment]
After creating a new account, I was unable to log into an existing one. I have met an issue. 

Steps to reproduce the behaviour:
1. Click on Generate new wallet
2. Log out from extension.
3. Open extension
4. Click on 'I agree"
5. Click on Retrieve Existing account
6. Enter Seed phrase
7. Click on Import account
8. See an error on Pop-up:

![Знімок екрана 2020-09-21 о 5 56 21 пп](https://user-images.githubusercontent.com/69896204/93783769-cb728380-fc34-11ea-89f3-fb9af8f7db42.png)

Browser: Brave
Extension: ver. 0.3.3.

**Comment by mradkov** [comment]
I will try to reproduce this now.

**Comment by mradkov** [comment]
I was not able to reproduce this issue. 🤷

**Comment by Liubov-crypto** [comment]
This happens when I have deleted an existing wallet. And after that, I want to create a new one:

https://youtu.be/scDXIY6UMjs
