### ISSUE TITLE
Problem with fetching tx

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-wallet#537]
> When I don't use the iframe wallet for a while, I get a problem to use my iframe wallet after a break.
> I mean I don't use the sh site for a few minutes, use other tabs, then I went back to the sh site and found this:

![da75c441-d204-4b52-9e71-47223d3ab6e7](https://user-images.githubusercontent.com/13139371/94683353-aa8dea80-0326-11eb-98e6-72f4176c31e4.png)

```json
{
  "id": "106",
  "appVersion": "0.3.3",
  "browser": {
    "name": "chrome",
    "version": "85.0.4183",
    "os": "Mac OS"
  },
  "error": {
    "message": "While calling getTxByAccount (account, {limit, page}), Network Error",
    "stack": "Error: While calling getTxByAccount (account, {limit, page}), Network Error\n    at e.exports (https://wallet.superhero.com/popup.js:41:620724)\n    at XMLHttpRequest.h.onerror (https://wallet.superhero.com/popup.js:41:619689)",
    "type": "unhandledrejection"
  },
  "platform": "web",
  "description": null,
  "time": "1601462124238",
  "createdAt": "2020-09-30T11:36:27.619Z",
  "updatedAt": "2020-09-30T11:36:27.619Z"
}
```

**Comment by elitedev1314520** [comment]
I would like to help with this issue.
Is there anyone I can help with?

**Comment by mradkov** [comment]
> I would like to help with this issue.
> 
> Is there anyone I can help with?

Feel free to provide PR. But keep in mind we might fix it first if it becomes more urgent.
