### ISSUE TITLE
Scroll with Chrome iOS

### ISSUE THREAD

**Issue by shapkarin** [aeternity/superhero-wallet#544]
There is no able to scroll with Chrome at iOS. And in this case buttons "Generate New Wallet" and "Retrieve existing account" are visible if device height is allow to see them.

<img src="https://user-images.githubusercontent.com/1463086/95171826-2670b280-07bf-11eb-9df1-8b4d88c06174.jpeg" height="740px" />

iOS 14.0.1
Chrome 85.0.4183.109

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problem. Feel free to reopen this issue, if it will pop up in next versions.

**Comment by shapkarin** [comment]
@CedrikNikita great!
