### ISSUE TITLE
The iframe wallet is always initialized even if the user is using the extension

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#550]
The iframe wallet is always initialized even if the user is using the extension. User needs to reload the page several times for the extension to connect to the superhero ui. 

Steps to reproduce the behaviour: 
1. I have registered a new wallet (with 0 balance)
2. Go to superhero.com
3. Refreshed the page to connect the extension with superhero.com
4. The connection does not happen immediately. The user needs to refresh the page so that my profile tab appears on the superhero ui
5. After the connection superhero ui does not correctly display user info
6. superhero ui shows the balance of the previous wallet

![Знімок екрана 2020-10-09 о 4 58 14 пп](https://user-images.githubusercontent.com/69896204/95743171-f97a3f00-0c99-11eb-8b2c-d86552975831.png)

![Знімок екрана 2020-10-09 о 4 59 00 пп](https://user-images.githubusercontent.com/69896204/95743192-0303a700-0c9a-11eb-8717-7ede9540d2eb.png)

![Знімок екрана 2020-10-09 о 4 59 00 пп](https://user-images.githubusercontent.com/69896204/95743199-06972e00-0c9a-11eb-8780-bdc1fde522fc.png)

OS: Mac 10.15.7
Browsers: Chrome, FF, Brave
Extension ver: 5d91965 / v.0.3.3

**Comment by davidyuk** [comment]
this may be fixed by #554

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problem. Feel free to reopen this issue, if it will pop up in next versions.
