### ISSUE TITLE
Youtube tip button gets injected multiple times

### ISSUE THREAD

**Issue by gorbak25** [aeternity/superhero-wallet#557]
**Describe the bug**
![image](https://user-images.githubusercontent.com/1352848/96509115-df250000-125b-11eb-8a40-215f96c5d294.png)

**To Reproduce**
1. Install superhero firefox extension
2. Go to youtube
3. Watch videos until you encounter this bug

**Expected behavior**
The Superhero tip button is displayed only once

**Software:**
 - OS: ArchLinux
 - Browser: Firefox 81.0.2
-  Superhero 5d91965 / v.0.3.3

**Comment by Liubov-crypto** [comment]
Not reproducible on the current product branch, can be closed.
