### ISSUE TITLE
Misleading rounding

### ISSUE THREAD

**Issue by gorbak25** [aeternity/superhero-wallet#558]
I've transferred 1 aetto to my account using an erlang console.
https://mainnet.aeternal.io/transactions/th_2ocsmXbg5djrKPxrEj3s3upBYXvTLPjJthQyDePoyjJdkLeCQN
1 aetto gets rounded to 0.01 AE in the wallet which is very misleading.

**Comment by CedrikNikita** [comment]
fixed in #883
