### ISSUE TITLE
Missing transaction history

### ISSUE THREAD

**Issue by gorbak25** [aeternity/superhero-wallet#559]
When performing a lot of transfers or receiving a lot of tokens, old transactions aren't available in the history :(
There is no option in the wallet to fetch more TXs from the middleware, ideally the history should be stored in local storage :(
If I want to remove someone's transaction history, all I need to do is to spam them with 1 aetto transfers from multiple accounts -.-
Here is my account: ak_2VMBcnJQgzQQeQa6SgCgufYiRqgvoY9dXHR11ixqygWnWGfSah

**Comment by mradkov** [comment]
We are facing corrupt data from the old mdw rendering this lack of tx history.

We are currently working on introducing the new mdw which will help solving this.

**Comment by davidyuk** [comment]
> ideally the history should be stored in local storage

won't we have problems syncing this data between user's devices?

**Comment by gorbak25** [comment]
> > ideally the history should be stored in local storage
> 
> won't we have problems syncing this data between user's devices?

This is where the middleware should be used. It doesn't make sense to retrieve all N transactions the user did from the middleware every time I open my wallet - only the most recent transactions.

**Comment by davidyuk** [comment]
Yes, and to load further transactions using infinite scrolling as we did in the Base aepp. I can't get why we need localStorage here.

**Comment by CedrikNikita** [comment]
Can't reproduce this issue. Feel free to reopen this issue, if it will pop up in next versions.
