### ISSUE TITLE
Creating a new account after deleting an existing one

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#560]
If you delete an existing account from the wallet and then want to create a new one, you get this error:

![Знімок екрана 2020-10-09 о 4 05 35 пп](https://user-images.githubusercontent.com/69896204/96580450-f5c16a80-12e0-11eb-9037-643788fe861b.png)

Steps to reproduce bug: 
1. Delete existing account
2. Close the wallet
3. Open wallet and create a new account
4. See the error.

Buttons in the popup are not responsive. User cannot create report and send via wallet.

Browser: Chrome, Brave
OS: Mac 10.15.7
superhero ui 0.2.1
superhero wallet 5d91965 / v.0.3.3

**Comment by Liubov-crypto** [comment]
Also, the following error appears in firefox when performing the following steps: 
1. Delete existing account
2. Close the wallet
3. Open wallet and create a new account
4. See the error: 

![Знімок екрана 2020-10-21 о 5 21 22 пп](https://user-images.githubusercontent.com/69896204/96733755-7d32da80-13c2-11eb-942b-94b3ae5d2213.png)

Browser: FireFox
OS: Mac 10.15.7
superhero ui 0.2.1
superhero wallet 5d91965 / v.0.3.3

**Comment by davidyuk** [comment]
well, the first one soould be fixed by 74e3da67ee79a74ac411b654bc5873aa0a019709
@mradkov can we make a new release?

**Comment by CedrikNikita** [comment]
Fixed by this PR https://github.com/aeternity/superhero-wallet/pull/650
