### ISSUE TITLE
Include the TIPPING_V2 contract to claiming as well

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-wallet#563]
Shouldn't we also include the TIPPING_V2 contract here so we can pass claims for the new contract? 🤔

_Originally posted by @mradkov in https://github.com/aeternity/superhero-wallet/pull/519#discussion_r508272402_

**Comment by CedrikNikita** [comment]
fixed in https://github.com/aeternity/superhero-wallet/pull/2080
