### ISSUE TITLE
Display the amount in the selected currency opposite the tokens

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#564]
I think it would be useful/nice to display the amount in the selected currency opposite of the tokens on the superhero ui (if user use the extension). 
Now zeros are displayed there: 
![Знімок екрана 2020-10-21 о 6 07 23 пп](https://user-images.githubusercontent.com/69896204/96740699-bde22200-13c9-11eb-9d3e-f7e644863d18.png)

@onvisions what do you think about it?

**Comment by CedrikNikita** [comment]
This issue is fixed in https://github.com/aeternity/superhero-ui/pull/899, Feel free to reopen this issue, if it will pop up in next versions.
