### ISSUE TITLE
Creating account right after deleting previous doesn't work

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/superhero-wallet#570]
Steps to reproduce:
1. Create an account
2. Delete an account
3. Create an account (without closing the extension)
4. Close extension
5. Open extension; You don't have an account view, because you somehow doesn't create a new account
![Remove account](https://user-images.githubusercontent.com/9008074/97158351-054f2080-17c5-11eb-83f0-433cec6436ab.gif)

**Comment by davidyuk** [comment]
probably it is the same bug #560

**Comment by CedrikNikita** [comment]
Fixed by this PR https://github.com/aeternity/superhero-wallet/pull/650
