### ISSUE TITLE
Initialization error if you do not use the wallet for some time

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#575]
The wallet freezes if you do not use it for a while - a couple of seconds.

1. Login to the wallet
2. Click somewhere to make it disappear
3. Wait a while, a couple of seconds
4. Click on the extension icon
5. See an error:

![Знімок екрана 2020-10-29 о 6 37 37 пп](https://user-images.githubusercontent.com/69896204/97614005-13e64380-1a22-11eb-8663-c0ba9d4128ef.png)

 - OS:  iOS 10.15.7
 - Browser : chrome, 
 - Wallet: Superhero 5d91965 / v.0.3.3

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problem. Feel free to reopen this issue, if it will pop up in next versions.
