### ISSUE TITLE
Can't register a new .chain name in the wallet

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#581]
Steps to reproduce the behaviour:
1. Login into the wallet
2. Click on Burger Menu on Top
3. Click on Names
4. Click on the Register button
5. Enter a random name 
6. Click on +
7. See the error: 

![Знімок екрана 2020-11-04 о 1 40 18 пп](https://user-images.githubusercontent.com/69896204/98109198-d95b2b80-1ea5-11eb-8160-62706cc9f64d.png)

This issue is reproducible in both web wallet and extensions (Chrome, FF).

Browser: chrome, Version 86.0.4240 (Mac OS)
OS: 10.15.7
Superhero ff63864 / v.0.4.0

**Comment by etharner** [comment]
This bug is related to permissions. It will be fixed in https://github.com/aeternity/superhero-wallet/pull/584
