### ISSUE TITLE
The error logging into a new account after deleting an existing one

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#582]
When I logged into my account after deleting the previous one, I encountered an error.

Steps to reproduce the behaviour:
1. Go to https://release-0-4-0.wallet.z52da5wt.xyz/account
2. Delete an existing account
3. Login into a new account
4. See error:

When you delete an account:

![Знімок екрана 2020-11-04 о 4 55 46 пп](https://user-images.githubusercontent.com/69896204/98149826-61f1c000-1ed6-11eb-9f31-22032f9ff9ee.png)
![Знімок екрана 2020-11-04 о 4 55 57 пп](https://user-images.githubusercontent.com/69896204/98149855-6fa74580-1ed6-11eb-9478-f4ad42df0293.png)

Tried to log in:
![Знімок екрана 2020-11-04 о 1 59 36 пп](https://user-images.githubusercontent.com/69896204/98149700-37076c00-1ed6-11eb-85d1-bef14c72459d.png)

Also, there was a problem with sending a report through the wallet:
![Знімок екрана 2020-11-04 о 2 00 11 пп](https://user-images.githubusercontent.com/69896204/98149730-44bcf180-1ed6-11eb-9382-df05c29a73f1.png)

![Знімок екрана 2020-11-04 о 2 00 23 пп](https://user-images.githubusercontent.com/69896204/98149779-57372b00-1ed6-11eb-89bb-9c26a9561d5c.png)

The same error is reproduced in FF:
![Знімок екрана 2020-11-04 о 7 50 25 пп](https://user-images.githubusercontent.com/69896204/98150392-3de2ae80-1ed7-11eb-87d3-d6118674708c.png)
![Знімок екрана 2020-11-04 о 7 50 39 пп](https://user-images.githubusercontent.com/69896204/98150419-4aff9d80-1ed7-11eb-9008-815893515bdf.png)

Mac OS: 10.15.7
Superhero ff63864 / v.0.4.0
Chrome, Version 86.0.4240 (Mac OS)
FF, version 82 (Mac OS)

**Comment by Liubov-crypto** [comment]
Not all fields are translated into Chinese:
![Знімок екрана 2020-11-04 о 1 06 50 пп](https://user-images.githubusercontent.com/69896204/98151641-286e8400-1ed9-11eb-9b64-c93c913c2219.png)
![Знімок екрана 2020-11-04 о 1 07 49 пп](https://user-images.githubusercontent.com/69896204/98151655-315f5580-1ed9-11eb-8c05-bf8bdf025389.png)
![Знімок екрана 2020-11-04 о 8 07 45 пп](https://user-images.githubusercontent.com/69896204/98151805-6a97c580-1ed9-11eb-9d9d-43faf58a97e2.png)

After claiming back, the field name changed to English
![Знімок екрана 2020-11-04 о 8 08 37 пп](https://user-images.githubusercontent.com/69896204/98151883-89965780-1ed9-11eb-999d-393d5704da62.png)

![Знімок екрана 2020-11-04 о 8 11 22 пп](https://user-images.githubusercontent.com/69896204/98152142-eabe2b00-1ed9-11eb-9d09-473326c3fc6e.png)
![Знімок екрана 2020-11-04 о 8 12 14 пп](https://user-images.githubusercontent.com/69896204/98152219-0b868080-1eda-11eb-8076-fb4c85b5a288.png)
![Знімок екрана 2020-11-04 о 8 12 41 пп](https://user-images.githubusercontent.com/69896204/98152261-1a6d3300-1eda-11eb-8b7a-41a9823ce9ee.png)

Also, if the wallet is minimized then the Chinese language is automatically changed to English. I don’t know how convenient it will be for Chinese users to constantly change the language.

**Comment by CedrikNikita** [comment]
Fixed by #650 and #678.
