### ISSUE TITLE
Permission settings are missed on the settings page

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-wallet#585]
<img width="549" alt="Screenshot 2020-11-06 at 14 59 27" src="https://user-images.githubusercontent.com/9007851/98363869-c6c92980-2040-11eb-809c-e0ef90844fad.png">

**Comment by etharner** [comment]
Will be fixed in https://github.com/aeternity/superhero-wallet/pull/584

**Comment by davidyuk** [comment]
For me would be fine to fix it in a separate one

**Comment by mradkov** [comment]
> For me would be fine to fix it in a separate one

I support this being added in separate PR as well. But if @etharner you think you can smuggle it in #584 - also fine for me.

**Comment by Liubov-crypto** [comment]
I checked, looks good for me. 
A little strange design in safari: 
![Безіменний 26](https://user-images.githubusercontent.com/69896204/99387247-53df6e80-28dc-11eb-8971-08fdaa6d3d6e.png)

**Comment by davidyuk** [comment]
> A little strange design in safari

Please, create a separate issue for this.

**Comment by Liubov-crypto** [comment]
> > A little strange design in safari
> 
> Please, create a separate issue for this.

done. transferred to #639
