### ISSUE TITLE
Activity - broken sort by date

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#598]
Web wallet: https://hotfix-update-cordova.wallet.z52da5wt.xyz/account
Send tip - pass
Claim tip - pass
Withdraw - pass/via scan pass
Invite link- pass
Top Up - no for web
Activity - broken sort by date

![Знімок екрана 2020-11-11 о 6 44 18 пп](https://user-images.githubusercontent.com/69896204/98842128-c3270f80-2451-11eb-8e86-335035daa34c.png)

Register name - failed
![Знімок екрана 2020-11-11 о 6 49 02 пп](https://user-images.githubusercontent.com/69896204/98842088-b4d8f380-2451-11eb-915f-905f20ed3001.png)

**Comment by davidyuk** [comment]
The first issue looks fixed on the develop branch:

<img width="341" alt="Screenshot 2020-11-16 at 10 50 28" src="https://user-images.githubusercontent.com/9007851/99225714-8b291f00-27f9-11eb-9f4c-396efea6a868.png">

I'm proposing to close this one and to extract the register name issue into a separate (if it is not fixed yet or there is no the same issue already).

**Comment by Liubov-crypto** [comment]
> The first issue looks fixed on the develop branch:
> 
> <img alt="Screenshot 2020-11-16 at 10 50 28" width="341" src="https://user-images.githubusercontent.com/9007851/99225714-8b291f00-27f9-11eb-9f4c-396efea6a868.png">
> 
> I'm proposing to close this one and to extract the register name issue into a separate (if it is not fixed yet or there is no the same issue already).

OK. There is already an issue with registering names and it has not been fixed yet.
