### ISSUE TITLE
The error when deleting an account and trying to sign in to an existing one

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#599]
I got an error when deleting an account and trying to sign in to an existing one:

![Знімок екрана 2020-11-11 о 5 33 09 пп](https://user-images.githubusercontent.com/69896204/98841977-8eb35380-2451-11eb-855b-695cb4e4200e.png)
![Знімок екрана 2020-11-11 о 5 38 38 пп](https://user-images.githubusercontent.com/69896204/98841994-94109e00-2451-11eb-862e-c58f326e88a8.png)
![Знімок екрана 2020-11-11 о 5 38 46 пп](https://user-images.githubusercontent.com/69896204/98842015-9b37ac00-2451-11eb-96d7-91e9d5772858.png)

FF/Chrome extension:
Send tip - pass
Claim tip - pass
Invite - pass
Top Up - pass
Register a name - failed
Withdraw - pass
Twitter/Youtube button - pass  
Activity - broken sort by date

**Comment by CedrikNikita** [comment]
Fixed by this PR #650
