### ISSUE TITLE
Names missing in wallet

### ISSUE THREAD

**Issue by thescientress** [aeternity/superhero-wallet#601]
**Describe the bug**
My registered chain names on Superhero are gone. Same with my names on base aepp

**Desktop (please complete the following information):**
 - OS: Catalina 10.15.7
 - Chrome 

I've been informed of the same problem by mobile users.

**Comment by mradkov** [comment]
Are you sure you are on mainnet?

**Comment by thescientress** [comment]
Yes, I am on mainnet.

**Comment by etharner** [comment]
@thescientress Can you post names you lost here?

**Comment by thescientress** [comment]
auntsteelbreaker.chain
barefoottiki.chain
Those are what I can remember.
From base aepp: thescientress.chain was there before

**Comment by etharner** [comment]
> auntsteelbreaker.chain
> barefoottiki.chain
> Those are what I can remember.
> From base aepp: thescientress.chain was there before

This names just expired
![image](https://user-images.githubusercontent.com/7098449/99256464-2bfef500-2861-11eb-8b95-af67a2cca630.png)
Current block height is far away
![image](https://user-images.githubusercontent.com/7098449/99256534-45a03c80-2861-11eb-953c-05aac45689bc.png)

I'm afraid that old mdw kept expired names
