### ISSUE TITLE
iOS: TestFlight has expired

### ISSUE THREAD

**Issue by bibzmibz** [aeternity/superhero-wallet#602]
**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 11
 - OS: [e.g. iOS8.1] 14.1
 - Browser [e.g. stock browser, safari] ....app!
 - Version [e.g. 22] idk, it won't start!

**Additional context**
the app won't start. 
![IMG_1420](https://user-images.githubusercontent.com/31322047/99235271-523f7900-27fe-11eb-8f70-1dec6a935136.PNG)

**Comment by mradkov** [comment]
We are aware of the issue and working on fixing it.

**Comment by mradkov** [comment]
This was fixed long time ago. Closing.
