### ISSUE TITLE
When enabling/disabling name autoextend the name screen is shown

### ISSUE THREAD

**Issue by gorbak25** [aeternity/superhero-wallet#605]
Browser: Firefox
Version:  Superhero ff63864 / v.0.4.0 

When clicking the auto-extend tickbox on a name which I own I'm sent to the screen with name details. When I click the tickbox I'm not expecting to be sent to another screen. Going back to my names it turns out the tickbox was indeed activated.

**Comment by Liubov-crypto** [comment]
I can't reproduce this error. When I click on auto-extend in my wallet it doesn't redirect me to another screen.

**Comment by gorbak25** [comment]
![output](https://user-images.githubusercontent.com/1352848/99413384-01ab4700-28f6-11eb-956c-73aa06b27875.gif)
:man_shrugging:
