### ISSUE TITLE
When doing anything with AENS it just fails with "Value undefined is not type of number"

### ISSUE THREAD

**Issue by gorbak25** [aeternity/superhero-wallet#606]
Browser: Firefox
Version:  Superhero ff63864 / v.0.4.0 

When doing anything with AENS it just fails with "Value undefined is not type of number".
I'm unable to extend my names, claim new names or participate in name auctions.

**Comment by mradkov** [comment]
This is already resolved in the `develop` branch and will be preparing a new release now.

**Comment by gorbak25** [comment]
Fixed on master
