### ISSUE TITLE
Error while trying to register a new name from chrome extension

### ISSUE THREAD

**Issue by omar-saadoun** [aeternity/superhero-wallet#611]
**Describe the bug**
I created a new wallet topped up with enough tokens (450AE ) and I get an error when registering a chain name, tried many different ones with the same issue.

**To Reproduce**
1.Downloaded the new version (last one)
2. Created a new wallet
3. Backup my seed
4. Tried to register mynewchainnameomar.chain
5. get error: "Value undefined is not type of number"

**Expected behavior**
It should allow me to register a name

**Screenshots**
![image](https://user-images.githubusercontent.com/10965573/99403278-0a395880-28c9-11eb-8589-25105f557601.png)

![image](https://user-images.githubusercontent.com/10965573/99403229-fdb50000-28c8-11eb-9535-f2f2bcb99061.png)

**Desktop (please complete the following information):**
 - OS: MacOs Catalina 10.15.6
 - Browser Chrome 
 - Version Version 86.0.4240.198 (Official Build) (x86_64)

**Comment by thescientress** [comment]
Same problem for me.

**Comment by etharner** [comment]
@omar-saadoun @thescientress This issue was fixed among other AENS problems 2 days ago here https://github.com/aeternity/superhero-wallet/pull/603 and will be available with next release.
