### ISSUE TITLE
Zero balance at fiat section and select currency is under the menu section.

### ISSUE THREAD

**Issue by shapkarin** [aeternity/superhero-wallet#620]
Not sure if that is not a duplicate or maybe it's a new bug. At the web wallet at https://wallet.superhero.com/account there is two bugs:
1. Zero balance at fiat section.
2. List that helps to select currency is under the menu section.
<img width="450" alt="Снимок экрана 2020-11-19 в 01 11 26" src="https://user-images.githubusercontent.com/1463086/99594368-2857a380-2a04-11eb-9b9b-8e813af5f0fd.png">

**Comment by davidyuk** [comment]
Unfortunately, I can't reproduce these issues:

<img width="694" alt="Screenshot 2020-11-19 at 08 42 24" src="https://user-images.githubusercontent.com/9007851/99626395-27923200-2a43-11eb-87a1-3b2048a78cea.png">

<img width="642" alt="Screenshot 2020-11-19 at 08 45 14" src="https://user-images.githubusercontent.com/9007851/99626571-8c4d8c80-2a43-11eb-8c34-643fb3a325b6.png">

<img width="704" alt="Screenshot 2020-11-19 at 08 45 20" src="https://user-images.githubusercontent.com/9007851/99626576-8f487d00-2a43-11eb-8a11-8daca78489c0.png">

**Comment by davidyuk** [comment]
Please reopen if the issue persists

**Comment by shapkarin** [comment]
> Please reopen if the issue persists

I will recheck it today's afternoon
