### ISSUE TITLE
An error after closing and opening the wallet

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#623]
After I close the wallet and then reopen it, an error appears:

![2020-11-19 11 18 25 дп](https://user-images.githubusercontent.com/69896204/99647652-bf4f4a80-2a5a-11eb-9f69-5a2e72451fd5.jpg)

Superhero 366bffd/v.0.4.2 for Android

**Comment by davidyuk** [comment]
I have problems reproducing this one. Do you have more precise instruction?

**Comment by Liubov-crypto** [comment]
> I have problems reproducing this one. Do you have more precise instruction?

It looks strange, but today I can't reproduce this error...

**Comment by Liubov-crypto** [comment]
I have reproduced this error today. I closed the wallet and did not use it for a while, then I opened it and got this error:

![Безіменний 0003](https://user-images.githubusercontent.com/69896204/99959423-a6fd6980-2d93-11eb-9944-37b1190bba72.png)

Superhero 366bffd/v.0.4.2 for Android

**Comment by Liubov-crypto** [comment]
Tested, now works on my side.

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problem. Feel free to reopen this issue, if it will pop up in next versions.
