### ISSUE TITLE
Unmined transactions are pending indefinitely

### ISSUE THREAD

**Issue by gorbak25** [aeternity/superhero-wallet#625]
When submitting an invalid transaction which goes past the wallet's builtin validation(spend tx to an unpayable contract account) the transaction is evicted from the mempool after some time. Unfortunately superhero wallet lists the transactions as pending indefinitely - Some invalid transactions long evicted from the mempool are listed as "pending" in the wallet :(

**Comment by davidyuk** [comment]
It is fixed it https://github.com/aeternity/superhero-wallet/pull/556/files#diff-5170c3bed35ddecb145bdd54e44cbff31894720804e29cb4c5c36672499e8f53R18, but that PR is not merged yet because of possible bugs
