### ISSUE TITLE
Superhero walet performs an unbeliviable amount of height queries

### ISSUE THREAD

**Issue by gorbak25** [aeternity/superhero-wallet#629]
Go to wallet.superhero.com and open the dev console...
![image](https://user-images.githubusercontent.com/1352848/99664246-2de6d500-2a68-11eb-9485-dcc6e9ebfbed.png)
The height usually changes every 3 minutes -.-

**Comment by davidyuk** [comment]
<img width="1387" alt="Screenshot 2020-11-19 at 20 30 38" src="https://user-images.githubusercontent.com/9007851/99701920-2d6d2f00-2aa6-11eb-8cd6-80eb91d2532e.png">

Well, I can't reproduce this. Can you specify the exact page that makes so lot of requests?

**Comment by gorbak25** [comment]
@davidyuk I have a lot of infinitely pending transactions in my wallet: https://github.com/aeternity/superhero-wallet/issues/625

**Comment by davidyuk** [comment]
That issue is closed, reopen it if the issue will persist in the next release
