### ISSUE TITLE
Don't ask for message signing is not working

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-wallet#630]
- install Chrome extension (current develop version)
- recover the account using mnemonic phrase
- open https://develop.aggregator.z52da5wt.xyz/
- connect to the extension
- confirm message signing
- switch "Don't ask for message signing"
- reload UI page
- confirm message signing

Repeating the last 3 steps you should notice that UI asks for message signing each time.

cc: @etharner

**Comment by etharner** [comment]
This is because permissions is checking only if app is in `NO_POPUP_AEPPS` list, for other apps popup always will appear. https://develop.aggregator.z52da5wt.xyz/ isn't in this list.
I've made it like that before introducing of aepp permissions, where I'm removing `NO_POPUP_AEPPS`

**Comment by davidyuk** [comment]
> introducing of aepp permissions

Do you mean per-domain permissions? Ok, let's close this after merging #584
