### ISSUE TITLE
Design bug in Safari

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#639]
Settings section in Safari looks strange. Small design bugs: 
![Безіменний 26](https://user-images.githubusercontent.com/69896204/99387247-53df6e80-28dc-11eb-8971-08fdaa6d3d6e.png)

@onvisions could you take a look, please?

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up again.
