### ISSUE TITLE
Back button from Names should go straight to dashboard

### ISSUE THREAD

**Issue by thescientress** [aeternity/superhero-wallet#644]
If I go to the Names section and click between Your Names, Auctions, and Register, the back button remembers this and serves more like an Internet back button. So if I've clicked between the three tabs 20 times, I would have to click the back button 21 times to go back to the dashboard/home screen. 

Back button should just go back to Home.

**Comment by davidyuk** [comment]
the issue on the same topic: https://github.com/aeternity/superhero-wallet/issues/465
