### ISSUE TITLE
Profile button is gone. Wallet loads old name. 

### ISSUE THREAD

**Issue by thescientress** [aeternity/superhero-wallet#645]
I do not see the edit profile button--was it intentionally removed? I can't find a way to edit the photo. 

Also, my web wallet loads an old chain name even though I've updated my name on the extension. 
![Screen Shot 2020-11-23 at 2 59 20 PM](https://user-images.githubusercontent.com/31926001/99936195-8cc88900-2d9d-11eb-9f67-a19aa642d1e1.png)

**Comment by Liubov-crypto** [comment]
I have no problem with the profile on sh UI, but if I change the name in the wallet, it also does not sync with superhero UI. The old name is displayed on superhero UI (the one that was synced for the first time).

![Безіменний 0005](https://user-images.githubusercontent.com/69896204/99969534-46762880-2da3-11eb-8130-112011590596.png)

**Comment by davidyuk** [comment]
> I do not see the edit profile button--was it intentionally removed? I can't find a way to edit the photo.

Are you sure that the wallet is connected to UI? Send the screenshot of comment input for instance (it should show your avatar).

**Comment by thescientress** [comment]
On the right it shows I'm logged in but using the old name, and the avatar is not updated. It doesn't seem to detect that I am the same user (you can see it's the same wallet address), and does not display my chain name. Many users are also just displayed as Fellow Superhero.

![Screen Shot 2020-11-25 at 12 48 50 PM](https://user-images.githubusercontent.com/31926001/100184554-b9ef7580-2f1c-11eb-89ea-856692f858af.png)

And no, doesn't look like they are connected. How do I do that? See comment input below.

![Screen Shot 2020-11-25 at 12 49 14 PM](https://user-images.githubusercontent.com/31926001/100184619-e1464280-2f1c-11eb-9f3c-255789ff6393.png)

**Comment by davidyuk** [comment]
> And no, doesn't look like they are connected. How do I do that?

Yes, they are not connected. After UI opened, the wallet should show the popups asking to connect them, but you may not see it if popups are not allowed.

**Comment by CedrikNikita** [comment]
This [PR](#668) is fixing old name showing. Connecting to the superhero-ui depending on showing popups. About more careful names fetching on the ui side see the discusion in https://github.com/aeternity/superhero-ui/issues/870
