### ISSUE TITLE
Sending an error results in an error.

### ISSUE THREAD

**Issue by thescientress** [aeternity/superhero-wallet#653]
Cleared my cache and restarted my computer, hoping that the profile button will show once my browser is refreshed. 
Got this error.

![Screen Shot 2020-11-24 at 2 56 44 PM](https://user-images.githubusercontent.com/31926001/100059163-93223800-2e65-11eb-8055-85cad26451fc.png)

Tried to send an error report, got this error instead. 

![Screen Shot 2020-11-24 at 2 57 27 PM](https://user-images.githubusercontent.com/31926001/100059253-b51bba80-2e65-11eb-8960-8253193cb011.png)

**Comment by thescientress** [comment]
This was from the web wallet btw.

**Comment by CedrikNikita** [comment]
> Cleared my cache and restarted my computer, hoping that the profile button will show once my browser is refreshed.
> Got this error.
> 
> ![Screen Shot 2020-11-24 at 2 56 44 PM](https://user-images.githubusercontent.com/31926001/100059163-93223800-2e65-11eb-8055-85cad26451fc.png)
> 
> Tried to send an error report, got this error instead.
> 
> ![Screen Shot 2020-11-24 at 2 57 27 PM](https://user-images.githubusercontent.com/31926001/100059253-b51bba80-2e65-11eb-8960-8253193cb011.png)

You have to allow showing popups in your browser for the current page in order to gave access to your publicKey from the wallet to the superhero.com.

**Comment by thescientress** [comment]
Some of the pop-ups asking for permission did come up with no problems. But is it specific per subpage on Superhero?

**Comment by davidyuk** [comment]
> But is it specific per subpage on Superhero?

These permissions are specific to the domain. If you allowed popups on superhero.com, you have to do it separately for develop.aggregator.z52da5wt.xyz. Also, you may reset the permissions at the same time as the browser cache

> You have to allow showing popups in your browser for the current page in order to gave access to your publicKey from the wallet to the superhero.com

Anyway we should investigate why the report can't be sent
