### ISSUE TITLE
Failed to load avatar in the wallet

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#659]
After login, the avatar is not loaded in the wallet:

![wall1](https://user-images.githubusercontent.com/69896204/100208367-514ecb80-2f11-11eb-9aef-ca77abb6f6e2.png)

![errors in console](https://user-images.githubusercontent.com/69896204/100207975-de455500-2f10-11eb-9ece-f4e3a56e92dd.png)

Superhero 0953e89 / v.0.4.2

**Comment by davidyuk** [comment]
This looks like a load balancer misconfiguration that Keno has reported about in Wire. Is it still reproducible?

**Comment by Liubov-crypto** [comment]
Checked on development. Looks good now.
