### ISSUE TITLE
Smoother UX for comments

### ISSUE THREAD

**Issue by thescientress** [aeternity/superhero-wallet#663]
Just a suggestion: commenting shouldn't require loading a new screen to confirm. In general, if an action does not involve tokens/funds or anything security-related, simple actions like commenting should not require too much confirmation. Should be as smooth and seamless as regular social media and other forums. Example below:

![Screen Shot 2020-11-26 at 9 53 24 AM](https://user-images.githubusercontent.com/31926001/100298995-87518580-2fcd-11eb-8814-0d646e24d41e.png)
![Screen Shot 2020-11-26 at 9 53 35 AM](https://user-images.githubusercontent.com/31926001/100299003-8ae50c80-2fcd-11eb-8ca9-61962b0bbd96.png)

**Comment by mradkov** [comment]
Thanks for the suggestion. I think after the permissions per domain is implemented and set-up with a pre-defined state for `superhero.com` the users won't require to confirm popups for such actions.

**Comment by davidyuk** [comment]
Actually, after per-domain permissions users still have to confirm comments on mobile because of deeplinks.

**Comment by mradkov** [comment]
> Actually, after per-domain permissions users still have to confirm comments on mobile because of deeplinks.

Yeah, on mobile currently there is no other way around.

**Comment by davidyuk** [comment]
Maybe this is not so important to be able to prove that somebody has left a comment and we can use JWT instead of message signing?

**Comment by CedrikNikita** [comment]
fixed in https://github.com/aeternity/superhero-wallet/pull/1962
