### ISSUE TITLE
Login error with iframe on superhero.com

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#670]
I tried to log in to the iFrame wallet on superhero.com and got this error:

![Безіменний 2](https://user-images.githubusercontent.com/69896204/100349900-c7c2fa80-2ff1-11eb-90a1-02a22ff416b3.png)

![consol 1](https://user-images.githubusercontent.com/69896204/100349505-3eabc380-2ff1-11eb-9fb6-f535f810915f.png)

The error when sending a report:
![error report ](https://user-images.githubusercontent.com/69896204/100349529-48352b80-2ff1-11eb-86a5-4fb07693a8d4.png)
![error sending report](https://user-images.githubusercontent.com/69896204/100350178-28eace00-2ff2-11eb-9a46-d2222010dfa3.png)

Browser: Safari
Superhero 366bffd / v.0.4.2

**Comment by Liubov-crypto** [comment]
Checked, LGTM

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up again.
