### ISSUE TITLE
The error sending comments to Superhero UI via Android app

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#674]
I tested Android App and found that the first comment on the superhero UI was signed via the app, the second via the web wallet. This is strange since I checked the box - remember my choice (choose the application) when I sent the first comment.
Both comments in the picture were sent by me, one via the application, the second via the web wallet:
![2020-11-27 5 02 14 пп](https://user-images.githubusercontent.com/69896204/100462071-5d35bb80-30d2-11eb-91bf-7ea27f47f216.jpg)

Superhero 366bffd/v.0.4.2

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up again.
