### ISSUE TITLE
Notification balloon should disappear

### ISSUE THREAD

**Issue by thescientress** [aeternity/superhero-wallet#679]
Notification balloon (red numbers) should disappear after the user taps the notification icon and scrolls through the notifications list. 

Otherwise, people's wallets will have 99999999 on the icon at some point.

![sketch-1606745569300](https://user-images.githubusercontent.com/31926001/100620314-3dfc8f80-3359-11eb-85ee-5d6610e02978.png)

**Comment by etharner** [comment]
Should be fixed after this https://github.com/aeternity/superhero-wallet/pull/716
