### ISSUE TITLE
Deeplinking problem with Android mobile app when commenting on a post

### ISSUE THREAD

**Issue by ErkanKanden** [aeternity/superhero-wallet#681]
**Description of the bug:**

When I try to make a comment on Superhero.com for the second time (at the first time everything works fine) I get a deeplinking connection to my Superhero mobile wallet (Android) to confirm the comment. For some reason when making a comment the second time, the approval window inside the Superhero mobile app shows the text for the previous comment I approved before and when I try to continue it crashes. I need to manually close down the Superhero mobile app, re-create the comment I wanted to post on a tip on Superhero.com, and then when it comes to the deeplinking, my new comment correctly appears in the approval window in the Superhero mobile app and I can confirm it successfully. This is obviously a non-optimal condition for a good user experience (most users would be very unlikely to manually close their Superhero app, write a new comment and make a second intent to confirm the comment, just to make a simple comment on a post).

**To Reproduce**
1. Write a comment on any tip post on superhero.com
2. Confirm it through Superhero mobile app (Android)
3. Make another comment with a different text (e.g. same tip post)
4. Impossible to confirm on Superhero mobile app + shows previous comment text, not the new comment I wanted to post
5. Close Superhero mobile app
6. Write another comment and go to confirmation
7. Only now the newer comment text will appear in the confirmation window on Superhero mobile app (Android)

**Smartphone:**
 - Device: Samsung Galaxy A40
 - OS: Android 10
 - Browser: Chrome
 - Version 86.0.4240.198

**Comment by shapkarin** [comment]
@davidyuk thanks for the assignment, but I can't help - don't have any Android device.
