### ISSUE TITLE
Pending transactions

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#695]
When I tested this PR, I encountered an error in the FF extension but did not come across this error in a Chrome extension or web wallet. 
I send a tip on Youtube via the Youtube button, transactions in my wallet are marked as pending:

![er in ff](https://user-images.githubusercontent.com/69896204/100772622-832bca80-3408-11eb-96ef-d9dc24ad40ef.png)

While I see the same transaction in Chrome extension as sent:
FF extension - pending:
![ff sent1](https://user-images.githubusercontent.com/69896204/100772741-abb3c480-3408-11eb-8cd4-e394307b8fd5.png)
Chrome extension - sent:
![brave sent](https://user-images.githubusercontent.com/69896204/100772747-aeaeb500-3408-11eb-89c7-db37a57bf3a9.png)
https://mainnet.aeternal.io/transactions/th_g3Ep7MffvU3CRxq9EJG8oJ9FUWJ1RoBNhC3Lj6qVZV3FJvWet

When I send tip I got this error in the web wallet: 

![error on web](https://user-images.githubusercontent.com/69896204/100773010-00efd600-3409-11eb-8131-7f7b9bcbbccb.png)

and in FF extension: 

![eror in FF when sending tip](https://user-images.githubusercontent.com/69896204/100773100-19f88700-3409-11eb-9373-136e4d0db332.png)

**Comment by davidyuk** [comment]
seems that the same bug is explained in #662 
probably, I have broken the removal of pending transactions in this case, maybe @CedrikNikita can check it
