### ISSUE TITLE
FT transactions not showing in Activity history

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#697]
I withdraw / tip in FT, but I do not see these transactions in the activity history - only transactions with ae tokens.

![ft activity](https://user-images.githubusercontent.com/69896204/100905844-3102ac00-34d1-11eb-86ed-6dba70d85f8f.png)
![ft transaction list](https://user-images.githubusercontent.com/69896204/100905853-32cc6f80-34d1-11eb-9c57-9717a83b8a16.png)

I think it would be nice to add FT transactions to the activity history.

Superhero b500d03 / v.0.4.2

**Comment by davidyuk** [comment]
actually, FT transactions should be displayed as contract calls, but still, this doesn't look well

**Comment by Liubov-crypto** [comment]
> actually, FT transactions should be displayed as contract calls, but still, this doesn't look well

Agree. Maybe we can display contract calls in those FT in which transactions were made.
