### ISSUE TITLE
Unable to connect to choosen node

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#699]
The app does not connect to the mainnet:

![2020-12-02 8 26 07 пп](https://user-images.githubusercontent.com/69896204/100915169-aaec6280-34dc-11eb-8854-16ee188d9f53.jpg)

![2020-12-02 8 17 47 пп](https://user-images.githubusercontent.com/69896204/100914953-6bbe1180-34dc-11eb-9c6b-4fa61f8fac97.jpg)

Superhero 83b14be/v.0.4.1

**Comment by thescientress** [comment]
A few of us are having this exact same issue on mobile. Desktop works though.

**Comment by ErkanKanden** [comment]
Same here, issue still persists on Android mobile app.

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problem. Feel free to reopen this issue, if it will pop up in next versions.
