### ISSUE TITLE
Notification about my own actions?

### ISSUE THREAD

**Issue by thescientress** [aeternity/superhero-wallet#701]
I don't think I need a notification about my own comments/replies to my own posts/tips?

![Screen Shot 2020-12-03 at 12 12 50 PM](https://user-images.githubusercontent.com/31926001/100963314-137d2300-3561-11eb-9e17-b7fb9ea865ec.png)

**Comment by davidyuk** [comment]
I think the best would be to solve it on the backend side @kenodressel
