### ISSUE TITLE
4+ minute delay from sending tip to Feed display

### ISSUE THREAD

**Issue by thescientress** [aeternity/superhero-wallet#703]
From the time I sent a tip on the extension, I counted ~4min delay before the post is displayed on the feed. And ~8min delay before the tip shows up in the Activity on the Superhero wallet extension. Is this normal?

Using v0.4.2

**Comment by davidyuk** [comment]
@kenodressel how long should it take?

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up again.
