### ISSUE TITLE
Transactions from payable contracts are not displayed

### ISSUE THREAD

**Issue by martin-key** [aeternity/superhero-wallet#705]
**Describe the bug**
If a transaction to an address is invoked from a contract the transaction is not displayed in the wallet and also in the aeternal. 

**To Reproduce**
1. Make a payable smart contract
2. Deposit some coins in the smart contract
3. Invoke payable transaction to an ak address
4. See that the balance is updated but there is no transaction in the history

**Expected behavior**
To show the transaction in the history

**Comment by mradkov** [comment]
Its a known issue. Payable contract transactions are a side effect that is not indexed in the middleware yet, which is why the wallet is not displaying it yet either.

**Comment by martin-key** [comment]
If you point it to me I may check if I can resolve it.

**Comment by davidyuk** [comment]
The original issue is tracked in https://github.com/aeternity/ae_mdw/issues/24

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up again.
