### ISSUE TITLE
Cannot send tip via mobile

### ISSUE THREAD

**Issue by thescientress** [aeternity/superhero-wallet#711]
On mobile today, the Send Tip button remains greyed out even when all fields have been completed. 
Also, my mobile version is still on v0.4.1. Doesn't look like I can update to 0.4.2 on Android yet.
![Dec 7](https://user-images.githubusercontent.com/31926001/101338113-8109b600-38b7-11eb-91c5-2469e5da135f.png)

**Comment by CedrikNikita** [comment]
This issue exist on the 0.4.1 version. I wasn't able to reproduce it in the new versions.

**Comment by CedrikNikita** [comment]
New version is released. I wasn't able to reproduce it in the new versions. Feel free to reopen this issue, if this will be a problem in the new versions.
