### ISSUE TITLE
Unable to connect to chosen node

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#723]
I got an error while trying to connect to the mainnet network:

![connection with node](https://user-images.githubusercontent.com/69896204/101758078-96adf400-3ae0-11eb-86d7-757fd1c7f0bc.png)

FF browser
Superhero 1cafb53 / v.0.4.2 

This data is taken from a web wallet in the Safari browser:
![safari web wallet](https://user-images.githubusercontent.com/69896204/101759014-bbef3200-3ae1-11eb-9847-f2122b9c4c10.png)

**Comment by davidyuk** [comment]
@CedrikNikita just ensure that this problem is not on the side of wallet

**Comment by Liubov-crypto** [comment]
> @CedrikNikita just ensure that this problem is not on the side of wallet

should I move this issue to another section?

**Comment by CedrikNikita** [comment]
That what is goind on
```
Access to fetch at 'https://mainnet.aeternity.io/mdw/swagger/swagger.json'
from origin 'https://develop.wallet.z52da5wt.xyz' has been blocked by CORS policy: No 'Access-Control-Allow-Origin'
header is present on the requested resource.
If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

popup.js:1 GET https://mainnet.aeternity.io/mdw/swagger/swagger.json net::ERR_FAILED
```

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up again.
