### ISSUE TITLE
Color coding of transaction history

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-wallet#729]

**Comment by onvisions** [comment]
**Sent** and **Received** in each transaction from the list will have color coding applied as follows:

Sent: color: rgb(255 71 70 / .66);
Received: color: rgb(0 255 157 / .66);

**Comment by stanislav-slavov** [comment]
The colors are changed: 
- sent - #a32e2d;
- received - #00804e
As per our discussion. The "eye.png" is also changed
