### ISSUE TITLE
b is undefined

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-wallet#731]
The issue ocurred while trying to switch between networks (using build from develop branch - https://github.com/aeternity/superhero-wallet/commit/f404e6767d302c700fc5acc4ebd1422993280151)
<img width="445" alt="Screenshot 2020-12-15 at 14 03 57" src="https://user-images.githubusercontent.com/13139371/102212819-76b27200-3ede-11eb-9b18-9646129c437b.png">

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up again.
