### ISSUE TITLE
TypeError: spread non-iterable instance

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-wallet#732]
<img width="434" alt="Screenshot 2020-12-15 at 17 29 58" src="https://user-images.githubusercontent.com/13139371/102235661-3b726c00-3efb-11eb-97f8-c14acb6ed735.png">

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up again.
