### ISSUE TITLE
The white stripe in FF extension

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#760]
The white stripe in FF after the tip is sent: 
![white stripe in iframe wallet](https://user-images.githubusercontent.com/69896204/103097075-c0056e80-460e-11eb-9517-a77f7862048b.png)

**Comment by davidyuk** [comment]
The textarea is used here, it is difficult to size automatically. Proposing to use a plain div instead. The text selection should work the same in that case. Optionally, we can add a copy button.

**Comment by stanislav-slavov** [comment]
How about just hiding the scrollbar on FF as it is with other browsers?

**Comment by davidyuk** [comment]
This still a fragile approach, would be simpler to use a plain div there.
