### ISSUE TITLE
Don't align popup content by center

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-wallet#766]
https://github.com/aeternity/superhero-wallet/blob/1b72ae674c1f6a182d0a99b888206e4d5cd33f99/src/styles/global.scss#L235

Remove this and set align by center explicitly where it is needed. Currently, this global style breaks layout in random places, see 83fc30f3331b729c809fd1ab4d2fc7659d353f1e

**Comment by CedrikNikita** [comment]
fixed in https://github.com/aeternity/superhero-wallet/pull/859
