### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#768]
After logging into the wallet I got this issue:

![web wallet error](https://user-images.githubusercontent.com/69896204/104169708-a767c780-5408-11eb-84d8-48aaea00f49c.png)

and this: 
![FF error](https://user-images.githubusercontent.com/69896204/104169774-c2d2d280-5408-11eb-92c2-9e0d62a4ef99.png)

**Comment by mradkov** [comment]
Related to the middleware errors: https://github.com/aeternity/ae_mdw/issues/127
