### ISSUE TITLE
Without scrollbars, the user may read only the part of terms of service and think that he read them completely

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-wallet#778]
| Currently | The page length is clear |
|---|---|
| <img width="612" alt="Screenshot 2021-01-26 at 19 25 41" src="https://user-images.githubusercontent.com/9007851/105826424-71cbfc80-600c-11eb-8cfd-281e2712ca2d.png"> | <img width="612" alt="Screenshot 2021-01-26 at 19 26 47" src="https://user-images.githubusercontent.com/9007851/105826439-755f8380-600c-11eb-9e5d-7c39e8c672d4.png"> |

Can we solve the issues like [this](https://github.com/aeternity/superhero-wallet/pull/716#pullrequestreview-573009116) by disabling middle alignment on small screens (mobile) instead?

**Comment by Liubov-crypto** [comment]
@paolomolo do we need a scrollbar on the Terms page?
