### ISSUE TITLE
.chain name is supposed to be external link to user account (in blockchain explorer)

### ISSUE THREAD

**Issue by onvisions** [aeternity/superhero-wallet#781]
**.chain name** in the SH wallet account card was supposed (by design) to be external link to **user account** in blockchain explorer. 
Currently it's plain text according to @imollov. 
@mradkov I suggest we fix this issue. I'm also about to suggest consistent solution for too long .chain names but this shouldn't be blocking the missing link issue described above.

**Comment by CedrikNikita** [comment]
implemented in #892
