### ISSUE TITLE
Broken view Titles in iOS, errors on send

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-wallet#790]
![IMG_3015](https://user-images.githubusercontent.com/13139371/106442081-8b919780-6483-11eb-91c0-6c35a7e448eb.PNG)
![IMG_3016](https://user-images.githubusercontent.com/13139371/106442086-8cc2c480-6483-11eb-98b7-6e4b5fc85c1a.jpg)

**Comment by imollov** [comment]
The error on send is not reproducible at develop.
