### ISSUE TITLE
Not all registered names are shown in the wallet

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#802]
I have more than 11 registered names, but I cannot see them all in my wallet:

![1](https://user-images.githubusercontent.com/69896204/106727745-74ce7a80-6614-11eb-86c6-a3be0ed513fe.png)
![2](https://user-images.githubusercontent.com/69896204/106727763-77c96b00-6614-11eb-8123-cf9bff9d544b.png)

Superhero c9252ad / v.0.5.1

**Comment by mradkov** [comment]
Do you happen to have a list of all your names, so we can cross-check with the information being served by the middleware?

**Comment by Liubov-crypto** [comment]
> Do you happen to have a list of all your names, so we can cross-check with the information being served by the middleware?

These are the last .chain names that I registered and which I do not see on the list:
bigbrotherwatchonyou.chain
rainbowandcolorfull.chain

**Comment by Liubov-crypto** [comment]
I can't reproduce this error on the development branch (d8c89dd / v.0.6.0 ) now. The last names I registered are in the wallet. Many of the previous names have disappeared because I haven't extended them.
Btw, I didn't find these names  bigbrotherwatchonyou.chain and rainbowandcolorfull.chain in my wallet :-/

**Comment by Liubov-crypto** [comment]
I registered these names while testing 21cc06b, but I can't see them in my wallet:
veryverylongtestname.chain
TarantinoQuarantino.chain
arpadamacskakkiralya.chain

on develop version f559c42 / v.0.6.1 too.
