### ISSUE TITLE
AENS actions: Display fees in transaction history

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-wallet#818]
> Thank you. Did you got any problems while doing so, and are you able to see your active auctions in the wallet?

You are welcome! Every transaction went smoothly and I see my names in active auctions in the wallet. 
(I registered 3 names with web wallet, FF/Chrome extension on testnet.)

![names auction ](https://user-images.githubusercontent.com/69896204/107233605-712f5f00-6a2b-11eb-97b5-fb9741f01111.png)

Btw, by registering the names, I spent a few ae tokens, but these transactions show up with zero sum in the Activity. Is this normal behavior?
![activity ](https://user-images.githubusercontent.com/69896204/107233704-873d1f80-6a2b-11eb-9f7b-8183808f0ab1.png)

_Originally posted by @Liubov-crypto in https://github.com/aeternity/superhero-wallet/issues/814#issuecomment-775196864_

**Comment by onvisions** [comment]
Yes. Let's display values. This emphasizes even more the low value of transaction fees. Also the 0AE transactions really might cause some confusion making the user wonder as it this case. New design easily covers this case too:
![Screenshot(54)](https://user-images.githubusercontent.com/12225410/107674028-3170ad80-6c9f-11eb-8bda-b3469b8a8594.png)

**Comment by mradkov** [comment]
> @mradkov
> Yes. Let's display the Tx fee value. This will emphasize even more the low value of transaction fees. Also the 0 AE transactions really might cause confusion. I was also wondering why the value is zero. New design (see in Figma wallet UI project, test in prototype if you'd like) easily cover this case:
> ![Screenshot(54)](https://user-images.githubusercontent.com/12225410/107674028-3170ad80-6c9f-11eb-8bda-b3469b8a8594.png)

This still does not seem to look consistent. The contractCalls for FTs also have txFees (which are not displayed here).

**Comment by Liubov-crypto** [comment]
The old design defect, can be closed.
