### ISSUE TITLE
Camera permission request fails on FF

### ISSUE THREAD

**Issue by imollov** [aeternity/superhero-wallet#835]
![Screenshot 2021-02-19 at 14 15 20](https://user-images.githubusercontent.com/482351/108503810-a7879c80-72bd-11eb-893b-10598ec3fc68.png)

env:
* macOS BigSur 11.2.1
* FF 85.0.2
* SH Wallet 0.5.4

**Comment by Liubov-crypto** [comment]
This bug is not reproducible on the current product branch. Can be closed.
