### ISSUE TITLE
Cordova: QR code scanner title looks weird

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-wallet#839]
![photo_2021-02-22_17-54-40](https://user-images.githubusercontent.com/9007851/108725068-0b68ca00-7537-11eb-8db1-e0b0d1d6203a.jpg)

saw on #834 branch, but it shouldn't be related to changes made there

**Comment by davidyuk** [comment]
The same issue on iOS:
![photo_2021-02-22_18-47-30](https://user-images.githubusercontent.com/9007851/108732243-6eaa2a80-753e-11eb-8617-968d02c11837.jpg)

**Comment by CedrikNikita** [comment]
There is no such problem anymore in the develop branch. Feel free to reopen this issue, if this issue will appear again.
