### ISSUE TITLE
Make QR code scanner full screen in web version as in Cordova

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-wallet#840]
![photo_2021-02-22_18-02-13](https://user-images.githubusercontent.com/9007851/108726090-1a03b100-7538-11eb-8430-7a20bd84b7a3.jpg)

**Comment by Liubov-crypto** [comment]
@davidyuk @onvisions @paolomolo can we close this bug as we are using a new design?  

![scan qr ](https://user-images.githubusercontent.com/69896204/194536998-c83f565b-5d36-44e1-8b43-8925a13410e6.png)

**Comment by subhod-i** [comment]
Closing this in favor of the new design. Please feel free to reopen if needed.
