### ISSUE TITLE
QR scanner is not working on iOS

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-wallet#845]
related issue #833, see discussion in #834

<img src="https://user-images.githubusercontent.com/9007851/108733685-c9905180-753f-11eb-8f80-5b7cba933d44.png" width="50%" />

**Comment by maxkpower** [comment]
![IMG_1201](https://user-images.githubusercontent.com/25062001/122451927-f9f57300-cfa8-11eb-9e6d-c51f9f1760c8.PNG)

**Comment by imollov** [comment]
@maxkpower you need to open settings and allow camera permissions for the app. It should've asked you the first time you used the scanner.

As an improvement for this scenario, we can add a button in the dialog to directly open app settings?

**Comment by imollov** [comment]
> related issue #833, see discussion in #834
> 
> <img alt="" width="50%" src="https://user-images.githubusercontent.com/9007851/108733685-c9905180-753f-11eb-8f80-5b7cba933d44.png">

Not reproducible on develop. Tested on simulator and device.
