### ISSUE TITLE
Error with the compiler in FF and Chrome extensions

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#846]
Error with the compiler in FF and Chrome extensions:
![error when claim tokens  tokens were claimed](https://user-images.githubusercontent.com/69896204/108850900-86d88300-75ec-11eb-9050-67237103244f.png)
![switched btw nets ](https://user-images.githubusercontent.com/69896204/108851039-ab345f80-75ec-11eb-9249-853d85ebbe73.png)

Superhero 3e31c94 / v.0.5.6

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up again.
