### ISSUE TITLE
Search FT- tokens are displayed that do not contain search letters

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#849]
When searching for FT, tokens appear that do not contain the desired letters:
![ww](https://user-images.githubusercontent.com/69896204/108852152-e6835e00-75ed-11eb-9c38-9599eb686d15.png)

**Comment by AtanasKrondev** [comment]
Currently it is searching into the name, symbol and contract address of the token. 

Should we display the contract address to the users so they know it doesn't return wrong results?
Or maybe a checkbox to search or not for the contract address?

@CedrikNikita @mradkov @davidyuk

**Comment by davidyuk** [comment]
Maybe to include contract address into search if the search string is long enough? Like longer than 5-10 chars?
