### ISSUE TITLE
Truncated text goes outside content box

### ISSUE THREAD

**Issue by imollov** [aeternity/superhero-wallet#850]
![Screenshot 2021-02-23 at 16 44 17](https://user-images.githubusercontent.com/482351/108975176-e4251080-768e-11eb-86a5-a9e1dad6ab6a.png)

This makes it tricky to center vertically (ex: #812). It's currently workarounded with flex.

cc: @CedrikNikita

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up again.
