### ISSUE TITLE
New designs height

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-wallet#851]
@onvisions 
Aren't we planned to squeeze the new designs to a 600px height? I guess it should be done in other PR then, or designs should be provided for this.

_Originally posted by @CedrikNikita in https://github.com/aeternity/superhero-wallet/pull/820#discussion_r581760138_

**Comment by imollov** [comment]
https://github.com/aeternity/superhero-wallet/issues/880#issuecomment-801763593

**Comment by etharner** [comment]
Done in #872.
