### ISSUE TITLE
Update 4 specific color values across wallet and website UI. 

### ISSUE THREAD

**Issue by onvisions** [aeternity/superhero-wallet#861]
For the purpose of improved contrast and UI readability a few minor color adjustments need to be done updating 4 color values across the whole wallet and website UI. This shouldn't be much time consuming task with Search and Replace functionality used on the CSS.
The changes and the exact color values are described in the attached image below. Approved by @maxkpower .

![ColorFine-tuning](https://user-images.githubusercontent.com/12225410/109516580-05339a00-7ab1-11eb-853c-000cbaa9215c.png)

- [x] Change global colors
- [x] Change input on focus color

**Comment by CedrikNikita** [comment]
second part was fixed in https://github.com/aeternity/superhero-wallet/pull/911
