### ISSUE TITLE
Cursor and manage text selection

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/superhero-wallet#874]
I meant something else here.
The cursor should be pointer over interactive elements such as buttons (when they arre active, not disabled).
The cursor should be arrow over elements that are not interactive (although these elements can have hover effect applied). For example in the design here when the mouse cursor enters the whole card with browser buttons and info text the background changes its color (it has hover effect) but the cursor should remain arrow. 
The default behavior over texts is a separate matter. I don't see a problem to leave the default text cursor over larger portions of text. However I think @davidyuk is right text selection should be disallowed for most of the places with a **few exceptions.**
I think text selection will be useful where we have **"Terms of use"**, other meaningful texts that the user may want to copy and for the **addresses** (although we have "copy" button...).

**Example:**

![Screenshot(82)](https://user-images.githubusercontent.com/12225410/110316059-d8ccd000-8012-11eb-9df5-71b8c883d4ae.png)

_Originally posted by @onvisions in https://github.com/aeternity/superhero-wallet/pull/869#discussion_r589348093_

**Comment by davidyuk** [comment]
In my opinion, we shouldn't break the default behavior for the current environment:
- in web version, most of the text should be selectable (as in most web apps)
- in browser extension version, looks like it should be selectable as well
- in Cordova, it shouldn't be selectable except for places like Terms of Use

Actually, won't be better to make Terms of Use a link to an external web page to be able to send it to desktop/print it/enable reader view?

**Comment by davidyuk** [comment]
The ability to select something in the web version may be useful, for example, for instant translation:
![Screenshot 2021-03-09 at 14 26 23](https://user-images.githubusercontent.com/9007851/110481566-c2993f80-80f8-11eb-8736-79f898377251.png)
or to easily Google an error message.
