### ISSUE TITLE
Use plain css instead of vue-flickity

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-wallet#894]
Seems that we are able to implement it by ourselves.
- for previous/next buttons use [smooth scrolling](https://css-tricks.com/snippets/jquery/smooth-scrolling/)
- for scrolling with a finger on mobile enable snapping using [`scroll-snap-*`](https://css-tricks.com/practical-css-scroll-snapping/#example-2-horizontal-slider) properties 

Current state:
https://github.com/aeternity/superhero-wallet/blob/2b28c49ea382f8934d92de99f0488bb5b1292f77/src/popup/router/components/MenuCarousel.vue#L3-L27

cc: @etharner @imollov

**Comment by etharner** [comment]
@davidyuk I've already made my own solution and will publish it here https://github.com/aeternity/superhero-wallet/pull/872

**Comment by imollov** [comment]
Anything wrong with `vue-flickity`? 

It's `651B` minified and gizipped. Not to mention already implemented with all the bells and whistles on all platforms.

Also, this probably won't be the final design of it, as changes will be required to add more buttons. Discussed with @onvisions.

**Comment by davidyuk** [comment]
> Anything wrong with vue-flickity?

It is not a CSS standard. I'm just curious is it possible to do the same using modern CSS, and to check will it work in modern browsers. If so then we don't be needed to deal with third-party code in the future to do similar things 🎉

**Comment by etharner** [comment]
> > I've already made my own solution last week
> 
> Interesting what you will use there 👀
> 
> > Anything wrong with vue-flickity?
> 
> It is not a CSS standard. I'm just curious is it possible to do the same using modern CSS, and to check will it work in modern browsers. If so then we don't be needed to deal with third-party code in the future to do similar things 🎉

I've made this quick solution last week https://codepen.io/deuseth/pen/MWbzwex, for me it's quite adjustable for design changes

**Comment by davidyuk** [comment]
Looks nice, but shouldn't it be swipeable with a finger? (cc: @onvisions) If so then the initially proposed approach would be useful

**Comment by CedrikNikita** [comment]
fixed in #1154
