### ISSUE TITLE
What happened to my name?

### ISSUE THREAD

**Issue by gorbak25** [aeternity/superhero-wallet#896]
![image](https://user-images.githubusercontent.com/1352848/111301268-4cde2800-8652-11eb-8632-93c36700eb62.png)
![image](https://user-images.githubusercontent.com/1352848/111301298-55cef980-8652-11eb-953f-aba6c4573c27.png)

**Comment by gorbak25** [comment]
gorbak25.chain -> gorbak2chain.5 <3

**Comment by davidyuk** [comment]
I believe it is because of the TruncateMid component. cc: @CedrikNikita

**Comment by CedrikNikita** [comment]
Was fixed here https://github.com/aeternity/superhero-wallet/pull/857

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up again.
