### ISSUE TITLE
The long token name is truncated in the dropdown menu and in the extension

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#898]
![tokens name](https://user-images.githubusercontent.com/69896204/110816501-12f8d480-8294-11eb-9e69-a263f088c42f.png)
![invite link 1](https://user-images.githubusercontent.com/69896204/110816576-2146f080-8294-11eb-86bd-387738281027.png)
![long nt](https://user-images.githubusercontent.com/69896204/110816672-39b70b00-8294-11eb-8670-1c7f1f2624bd.png)
![lonng tn](https://user-images.githubusercontent.com/69896204/110816694-40de1900-8294-11eb-966e-dfc931edae32.png)
![longggtn](https://user-images.githubusercontent.com/69896204/110816731-49ceea80-8294-11eb-9581-6033edca479f.png)

the long token name is outside the web wallet:
![token name1](https://user-images.githubusercontent.com/69896204/110816905-71be4e00-8294-11eb-89f2-cbd3a815b08f.png)
![tok name 2](https://user-images.githubusercontent.com/69896204/110816936-784cc580-8294-11eb-9cb5-69cbcbaa24d9.png)

Superhero 9d0ae45 / v.0.5.6

**Comment by mradkov** [comment]
@onvisions any suggestions on this? cc @maxkpower

**Comment by maxkpower** [comment]
I suggest we only show the initial 4 characters followed by (...) under _available_. On hover, we could do a small overlay of the whole name. 
@onvisions unless you have any better suggestions?

**Comment by onvisions** [comment]
@maxkpower @mradkov  No I'm ok with this solution suggested by Max for now. In the new designs there is enough space to show all characters of the token "short" name. 
![Screenshot_1](https://user-images.githubusercontent.com/12225410/111482924-044f6900-873d-11eb-92d8-d9067bd56d51.png)

For the select drop-downs (choose currency or token) I think it's better to follow the native  mobile app approach to displaying select option lists or something based on that. I will have to provide design but generally speaking it will be like a popup with select options so it will have enough room to show all 14 characters. Or might be something like this:

![17203c6efba30d00d5bdfcf09543fb6c](https://user-images.githubusercontent.com/12225410/111485025-ef73d500-873e-11eb-8c58-5c33d0ee2148.jpg)

Still there might be some places in UI where 14 characters "short name" (which is no longer a real "abbreviation" in this case) might be problematic to display. In such cases we may have the solution suggested by @maxkpower .

**Comment by CedrikNikita** [comment]
fixed in #1198
