### ISSUE TITLE
Error while viewing the tutorial (targetElement is null)

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#900]
![err in FF ](https://user-images.githubusercontent.com/69896204/111325591-8031ae80-8674-11eb-906d-ab99d0de78c2.png)
![err from console](https://user-images.githubusercontent.com/69896204/111325604-832c9f00-8674-11eb-8265-87df6df0e72b.png)
![target element error](https://user-images.githubusercontent.com/69896204/111325618-858ef900-8674-11eb-82ba-8b7a0dafb36a.png)
![err in FF extension ](https://user-images.githubusercontent.com/69896204/111325718-9dff1380-8674-11eb-9d29-805681ab45c4.png)
![при просмотре туториала 1](https://user-images.githubusercontent.com/69896204/111325725-a0fa0400-8674-11eb-8524-401a03ead90d.png)
![tutorial error](https://user-images.githubusercontent.com/69896204/111325733-a3f4f480-8674-11eb-8c5f-ea24c7a6b275.png)

Superhero 9d0ae45 / v.0.5.6

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up again.
