### ISSUE TITLE
Transactions appear with a delay in Tx history

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#901]
I see that the transaction appears in the Tx history in the processing status, after a while it disappears, after few minutes it appears as completed.
Example:
12.26 - sent 0.1 ae, appeared in Tx history at 12:49. 
12.44 - sent TIP - appeared in Tx history at12:48 
1:18 - sent 10 Davidyuk, - appeared in Tx history at 14:00

Superhero 9d0ae45 / v.0.5.6

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up again.
