### ISSUE TITLE
Names shown as revoked

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-wallet#902]
![Wire 2021-03-16 at 17-06-15](https://user-images.githubusercontent.com/13139371/111350366-b4b06500-868a-11eb-9ad1-50bc40754a6c.png)

**Comment by davidyuk** [comment]
What is this issue about? Should revoked names disappear without a label or should user be able to remove revoked names by himself or wallet should automatically claim revoked names back? cc: @CedrikNikita

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up again.
