### ISSUE TITLE
Error Get Tx by Account

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#906]
I got this issue  when sorting transactions by date on the Tx page (using develop branch Superhero 226adef / v.0.5.6 )

![1111](https://user-images.githubusercontent.com/69896204/111637609-4393bd80-8802-11eb-812e-36937770cfbf.png)
![errrr](https://user-images.githubusercontent.com/69896204/111637639-4c848f00-8802-11eb-80a6-ca74662ff51a.png)

referred in #537

**Comment by davidyuk** [comment]
as I see it is blocked by issues on the middleware side:
https://github.com/aeternity/ae_mdw/issues/106
https://github.com/aeternity/ae_mdw/issues/105
https://github.com/aeternity/ae_mdw/issues/104
https://github.com/aeternity/ae_mdw/issues/103
cc: @skkw

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up again.

**Comment by Liubov-crypto** [comment]
I can't reproduce this issue
