### ISSUE TITLE
Error when switching networks

### ISSUE THREAD

**Issue by imollov** [aeternity/superhero-wallet#907]
> <img alt="Screenshot 2021-03-17 at 16 09 53" width="386" src="https://user-images.githubusercontent.com/13139371/111481058-424b8d80-873b-11eb-80b4-998af0a51786.png">
...

Now I got this error when switched between networks.

_Originally posted by @Liubov-crypto in https://github.com/aeternity/superhero-wallet/issues/883#issuecomment-801130363_

tested on develop 226adef

quick findings:
* to reproduce you must have a ft transfer transaction
* seems like the available ft tokens in the state are not in sync with transactions for a quick moment after switching networks

related to #905

**Comment by imollov** [comment]
related to https://github.com/aeternity/superhero-wallet/issues/905

**Comment by Liubov-crypto** [comment]
Got this error when switching to the testnet: 
![en is undefined](https://user-images.githubusercontent.com/69896204/112873659-99057f80-90ca-11eb-8585-6629e5b6ac85.png)
![err on develop when sw to testnet](https://user-images.githubusercontent.com/69896204/112873666-9b67d980-90ca-11eb-9ff7-96ac1375ed3b.png)

![sw to the testnet ](https://user-images.githubusercontent.com/69896204/112873745-b89ca800-90ca-11eb-9f53-f9ca0b93bebc.png)


on develop branch eaeeb50 / v.0.5.6

**Comment by CedrikNikita** [comment]
fixed by #1159 and #1149
