### ISSUE TITLE
Ensure that LinkButton works correctly in Cordova

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-wallet#914]
https://github.com/aeternity/superhero-wallet/pull/883/files#diff-e1d2444ad6dfb690d8f59027f1f0288c979b9bed35e94e22ffa53a997ab00487R17
Isn't it necessary to call `event.preventDefault()` to block `<a href="..." />` navigation?
cc: @imollov

**Comment by imollov** [comment]
It works correctly in Cordova, surprisingly. For some reason after click is handled href doesn't follow. Not even if you go back to the app. Also no errors are logged.

I tried adding `href="javascript:..."` just to test and that code is executed after returning to the app. If it's a url nothing happens.

Anyway, I'm going to call `event.preventDefault()` explicitly, as suggested.
