### ISSUE TITLE
Recent transactions contain all transactions after opening the list of transactions

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-wallet#917]
this is a side effect of this workaround: https://github.com/aeternity/superhero-wallet/pull/883/files#diff-42c781502dd0badc5c59da2f8253cdbee661a4cb9ec87b7ad4703bad7fb0f4b3R125

**Comment by imollov** [comment]
How would you do it instead?

**Comment by davidyuk** [comment]
In the Base aepp we had a reactive variable returning an actual list of transactions with ability to request it to load next page. We can reuse it adding persistance to localStorage and accepting the amount of transactions to show. Then we will be able to use it in both transaction list and recent transactions.

https://github.com/aeternity/aepp-base/blob/92b4235bb3ae521a8b30956780d9880869e5c3be/src/store/plugins/ui/observables.js#L224-L336

**Comment by davidyuk** [comment]
In the short term you can rename `updateLatestTransactions` to general `setTransactions` and slice from there the necessary amount to show in the recent transaction list.
