### ISSUE TITLE
vue-i18n/no-dynamic-keys check is not working

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-wallet#919]
it is enabled here: https://github.com/aeternity/superhero-wallet/blob/d13029a7e4bd44d11b44ccbc698322943786322b/.eslintrc.js#L53
example of code it should prevent:
https://github.com/aeternity/superhero-wallet/blob/d13029a7e4bd44d11b44ccbc698322943786322b/src/popup/router/components/TransactionFilters.vue#L13

**Comment by subhod-i** [comment]
@CedrikNikita Is this still valid?
