### ISSUE TITLE
Refactor Plate component

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-wallet#920]
Notes after checking #903:
- use hard shadow instead of the border
- remove negative margins (won't be needed to hide it after finishing #872)
- I think `position: fixed` should be defined by the parent component, also consider using `sticky` instead
- at the end `overflow-x: hidden` shouldn't be needed
- remove extra div

cc: @imollov

**Comment by imollov** [comment]
@davidyuk any specific reason to use shadow instead of border?

**Comment by imollov** [comment]
resolved in https://github.com/aeternity/superhero-wallet/pull/872 and https://github.com/aeternity/superhero-wallet/pull/952
