### ISSUE TITLE
Error: Transaction build error.

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#947]
I tested pr#943 and when I used this link: invite/Yqk76XDXNGVMZiCVfzE9NGHwhbXiCAsah2bxVpevCGjdLeeqPaSBVR4CkAdLyb1a7HGn2RD69RDLxYF3rdL3MWouvTyyK got an error:  "Error: Transaction build error. {"amount":"-16820000000000 must be >= 0"}..." 

Maybe it should be changed to a friendlier message? Ex.: tokens from the invitation link have already been claimed.

**Comment by davidyuk** [comment]
it may be fixing by detecting negative amount and checking for it in https://github.com/aeternity/superhero-wallet/blob/3eb88816ccdfde4a9b7d7048834f40c3b18dbc2f/src/store/modules/invites.js#L26

**Comment by Liubov-crypto** [comment]
![transaction build error](https://user-images.githubusercontent.com/69896204/113875190-2ded3480-97bf-11eb-850a-5eb70fb4c895.png)
![transaction build error1](https://user-images.githubusercontent.com/69896204/113875216-32195200-97bf-11eb-94f5-fdede988b73f.png)
