### ISSUE TITLE
SyntaxError: JSON.parse (not obvious answer)

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#948]
I used this link for testing:
comment?id=26_v1&parentId=87&text=This%20is%20a%20test%20message!%20http%3A%2F%2Fexample.com&x-success=https%3A%2F%2Ffeature-refactor-links.wallet.z52da5wt.xyz%2Fartifacts%2Fdeeplink-test.html%3Fresult%3Dsuccess&x-cancel=https%3A%2F%2Ffeature-refactor-links.wallet.z52da5wt.xyz%2Fartifacts%2Fdeeplink-test.html%3Fresult%3Dcancel and got this issue: 

![comments id 26_v1](https://user-images.githubusercontent.com/69896204/113005500-35885a00-917d-11eb-8b69-5f40be93d95c.png)
![console](https://user-images.githubusercontent.com/69896204/113005359-14276e00-917d-11eb-8ee4-cb885dc50a7c.png)
![елем](https://user-images.githubusercontent.com/69896204/113005387-1a1d4f00-917d-11eb-863d-3817bad9cc7a.png)

Message from the network tab: Could not find parent comment with id 87

Can we change the message in the popup "SyntaxError: JSON.parse..." to an understandable answer?

**Comment by davidyuk** [comment]
the message was because the wallet was connected to testnet, but still, it is reasonable to handle this case at least to don't debug it the next time

**Comment by Liubov-crypto** [comment]
Can't reproduce it on the current development branch.
