### ISSUE TITLE
Duplicate keys detected error

### ISSUE THREAD

**Issue by imollov** [aeternity/superhero-wallet#949]
Recurring error message popping up on account/home page only on mainnet:
`Duplicate keys detected: 'th_N2xwWp2yYP1MKmmxFNXHCc9iohxBexP9UnKZ2jNUXDPHcfMS5'. This may cause an update error....`

tested on develop cd7a6b717098699f6f87165a24c5eef6716ab25c
tested with account ak_DUFY68J5QvRTDUEoAKSVXgYGovV86dyboNk8RVq3gvwQ1fQ5y

**Comment by davidyuk** [comment]
This bug is investigated in #1053
