### ISSUE TITLE
A large amount of tokens are truncated

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#963]
![tokens11](https://user-images.githubusercontent.com/69896204/114001797-efaa5080-9864-11eb-9210-643ab90bab23.png)

mentioned in https://github.com/aeternity/superhero-wallet/pull/872#issuecomment-808351121

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up again.
