### ISSUE TITLE
This Selected Token balance compared To is not a function

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#964]
I tried sending a tip with FT to example.com on the testnet and got this error:
![Wire 2021-04-08 at 09-23-59](https://user-images.githubusercontent.com/69896204/114002603-ae667080-9865-11eb-97e5-b25cca462159.png)

**Comment by imollov** [comment]
could not reproduce it on develop 4e1fab4bdf1f16be47f12aceacdc1ecb5f66159c

**Comment by Liubov-crypto** [comment]
> could not reproduce it on develop [4e1fab4](https://github.com/aeternity/superhero-wallet/commit/4e1fab4bdf1f16be47f12aceacdc1ecb5f66159c)

Rechecked, now I also can't reproduce this error in the development branch
 d8c89dd / v.0.6.0
