### ISSUE TITLE
All fungible tokens disappeared from the Balance tab

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#968]
After this error, all fungible tokens disappeared from the Balance tab:
![зображення_viber_2021-04-08_11-02-35](https://user-images.githubusercontent.com/69896204/113997042-71e44600-9860-11eb-8861-85bfe88f4346.png)

_Originally posted by @Liubov-crypto in https://github.com/aeternity/superhero-wallet/issues/957#issuecomment-815559362_

**Comment by CedrikNikita** [comment]
fixed in #1023
