### ISSUE TITLE
FF extension is hidden under the browser panel

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#974]
the FF extension is hidden under the panel and I cannot log in:
![hidden in FF](https://user-images.githubusercontent.com/69896204/114522474-1513d180-9c4c-11eb-89eb-f836fabf91b1.png)

Also reproducible in the latest release.

**Comment by gorbak25** [comment]
Got the same issue :(

**Comment by davidyuk** [comment]
duplicate of #973
