### ISSUE TITLE
Currency scrollbar affects the transaction scrollbar

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#996]
Currency scrollbar affects the transaction scrollbar:
https://user-images.githubusercontent.com/69896204/114845693-a5851a00-9de4-11eb-96c2-cee170351249.mov

**Comment by davidyuk** [comment]
I'm not sure, but it looks like a reasonable behavior: the whole page is scrolled after the nested component is scrolled till the end.

**Comment by Liubov-crypto** [comment]
> I'm not sure, but it looks like a reasonable behavior: the whole page is scrolled after the nested component is scrolled till the end.

 in that case, this is not an issue.
