### ISSUE TITLE
When changing tokens in the drop-down menu, the web wallet goes to the left

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#997]
When I change tokens in the dropdown menu wallet goes left (I can also do it manually using the left / right buttons on the keyboard):
![right side](https://user-images.githubusercontent.com/69896204/114849417-635dd780-9de8-11eb-92c0-3d10c7f306f4.png)

**Comment by davidyuk** [comment]
@onvisions do we have an agreement on how to handle in UI extremely big amounts of tokens?

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up again.
