### ISSUE TITLE
Retip error

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#998]
Retip error (https://superhero.com/tip/2846_v1):
![retip error](https://user-images.githubusercontent.com/69896204/114857520-074b8100-9df1-11eb-8329-acc3802f8dbf.png)
![retip err1](https://user-images.githubusercontent.com/69896204/114857530-09154480-9df1-11eb-8245-8864df7d767c.png)

Safari browser

**Comment by etharner** [comment]
Fixed in #994
